import type { MenuItem } from '../../src/types';

const NOW = Date.now();

export const menuItems: MenuItem[] = [

  // === VEG MEZZE ===
  {
    id: 'vm1',
    name: 'Hommous',
    description: 'Chickpea ground with olive oil, lemon juice and tahini',
    price: 795,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&q=80',
    allergens: ['Sesame'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm2', 'vm3', 'vm4', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm2',
    name: 'Moutabel (Baba Ghanouj)',
    description: 'Grilled aubergines ground with lemon juice and tahini',
    price: 835,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1609167830220-7164aa360951?w=800&q=80',
    allergens: ['Sesame'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm3', 'vm4', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm3',
    name: 'Foul Moudamas',
    description: 'Boiled fava beans ground with lemon juice, olive oil and garlic',
    price: 745,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm2', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm4',
    name: 'Trio of Hommous, Moutabel & Foul Moudamas',
    description: 'Chickpea, aubergine & broad bean dips served with warm Lebanese bread',
    price: 975,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    allergens: ['Sesame', 'Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vm7', 'vm13', 'vm8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm5',
    name: 'Kabis',
    description: 'Mixed pickles & olives',
    price: 875,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'mm4', 'mm8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm6',
    name: 'Tabbouleh',
    description: 'Chopped parsley, tomato, onion, mint, cracked wheat, lemon juice & olive oil',
    price: 1025,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bp1', 'bp2', 'mm1', 'mm2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm7',
    name: "Warak Enab B'Zeit",
    description: 'Vine leaves filled with rice, tomato, parsley, mint & onion, cooked in lemon juice & olive oil',
    price: 870,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1610614819753-ec0bda4ca6a3?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm6', 'pl1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm8',
    name: 'Labneh',
    description: 'Strained yogurt with olive oil & thyme',
    price: 740,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm4', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm9',
    name: 'Moussaka',
    description: 'Fried aubergines baked with tomato, onion, chickpea & peppers',
    price: 845,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd1', 'sd3', 'vm6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm10',
    name: "Bamia B'Zeit",
    description: 'Okra cooked with tomato, onions & olive oil',
    price: 850,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm11',
    name: 'Fatayer Sebanikh',
    description: 'Pastry with spinach, onions, pine kernels, lemon juice, olive oil & sumac',
    price: 790,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80',
    allergens: ['Gluten', 'Nuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vm1', 'vm8', 'pl1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm12',
    name: 'Sambousek Jebneh',
    description: 'Pastry filled with feta cheese',
    price: 795,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1606502973842-f64bc2785fe5?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vm1', 'vm8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm13',
    name: 'Falafel',
    description: 'Deep fried balls of broad bean & chickpeas with spices served with tahini',
    price: 835,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    allergens: ['Sesame'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm8', 'sd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm14',
    name: 'Batata Harra',
    description: 'Sauteed potatoes with onions, peppers, coriander, garlic, lemon & chilli',
    price: 820,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['mm3', 'mm4', 'pl1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm15',
    name: 'Halloumi',
    description: 'Grilled halloumi cheese with peppers',
    price: 940,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1599020792689-9fde458e7e67?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm6', 'vm16', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm16',
    name: 'Halloumi Kellaj',
    description: 'Thin halloumi cheese with zatar spice & olive oil grilled in Lebanese bread',
    price: 895,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: ['Milk', 'Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vm15', 'vm8', 'vm6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm17',
    name: 'Fattoush',
    description: 'Lettuce, tomato, cucumber, onion, mint, radish, sumac with toasted Lebanese bread, lemon & olive oil dressing',
    price: 690,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mm1', 'mm2', 'bp1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm18',
    name: 'Lentil Soup',
    description: 'Finely selected lentils cooked in cumin & olive oil, served with toasted Lebanese bread',
    price: 750,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vm6', 'vm17', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vm19',
    name: 'Salata Zeytoun',
    description: 'Cucumber, tomato, olives, mint parsley topped with toasted pine nuts and fried almonds dressed with lemon & extra virgin olive oil',
    price: 790,
    category: 'Veg Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    allergens: ['Nuts'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['bp1', 'bp2', 'mm1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === MEZZE (MEAT) ===
  {
    id: 'mm1',
    name: 'Laham Mashwi',
    description: 'Tender cubes of lamb grilled with onions & tomato served with spicy sauce',
    price: 1155,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm6', 'sd1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm2',
    name: 'Shish Taok',
    description: 'Boneless cubes of chicken marinated in olive oil, lemon & garlic',
    price: 860,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm6', 'sd1', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm3',
    name: 'Kafta Kebab',
    description: 'Grilled minced lamb with onion, parsley & spices',
    price: 875,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm14', 'sd1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm4',
    name: 'Chicken Shawarma',
    description: 'Thin slices of chicken marinated in garlic & spices',
    price: 795,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'mm12', 'sd1', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm5',
    name: 'Kastaletta',
    description: 'Lamb cutlets grilled with onions and peppers served with spicy sauce',
    price: 1195,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'vm6', 'vm19', 'sd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm6',
    name: 'Laham bil Bamia',
    description: 'Tender lamb cooked with okra, onions, coriander & garlic in tomato sauce',
    price: 1075,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd1', 'sd3', 'vm6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm7',
    name: 'Kafta ma Batata',
    description: 'Traditional home dish of lamb meatballs cooked with potatoes & coriander in a garlic tomato sauce',
    price: 845,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd1', 'sd3', 'vm6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm8',
    name: 'Lamb Shawarma',
    description: 'Thin slices of lamb marinated in vinegar, garlic and spices',
    price: 865,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'mm15', 'sd1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm9',
    name: 'Kafta bil Jeben',
    description: 'Grilled minced lamb topped with cheese & a spicy sauce',
    price: 1065,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: ['Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd1', 'sd3', 'vm6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm10',
    name: 'Samak Harra',
    description: 'Grilled salmon mixed with spicy vegetables',
    price: 1045,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    allergens: ['Fish'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd1', 'vm6', 'vm19'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm11',
    name: 'Sambousek Bil Lahmeh',
    description: 'Pastry filled with minced lamb and pine kernels',
    price: 840,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1606502973842-f64bc2785fe5?w=800&q=80',
    allergens: ['Gluten', 'Nuts'],
    available: true,
    pairedItemIds: ['vm1', 'mm12', 'pl1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm12',
    name: 'Hommous bil Shawarma',
    description: 'Hommous topped with chicken or lamb shawarma',
    price: 990,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1637939424701-8fa6e51b2e9a?w=800&q=80',
    allergens: ['Sesame'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'mm4', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm13',
    name: 'Arayes',
    description: 'Grilled Lebanese bread filled with minced lamb and pine kernels',
    price: 875,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: ['Gluten', 'Nuts'],
    available: true,
    pairedItemIds: ['vm1', 'vm8', 'vm5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm14',
    name: 'Kibbeh',
    description: 'Deep fried minced lamb, onions, pine kernels cased with cracked wheat, minced lamb & spices',
    price: 880,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1606502973842-f64bc2785fe5?w=800&q=80',
    allergens: ['Gluten', 'Nuts'],
    available: true,
    pairedItemIds: ['vm1', 'vm8', 'pl1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm15',
    name: 'Hommous Awarma',
    description: 'Hommous topped with cooked minced lamb, pine kernels and almonds',
    price: 990,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1637939424701-8fa6e51b2e9a?w=800&q=80',
    allergens: ['Sesame', 'Nuts'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mm16',
    name: 'Qraydas',
    description: 'Grilled King prawns marinated in olive oil, garlic & lemon',
    price: 1350,
    category: 'Mezze',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    allergens: ['Crustaceans'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm19', 'sd1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === BIG PLATES ===
  {
    id: 'bp1',
    name: 'Kharouf Mashwi',
    description: 'Braised shank of lamb marinated in special herbs & spices, served with lamb fried rice',
    price: 2895,
    category: 'Big Plates',
    imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
    allergens: ['Nuts'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm6', 'vm19', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bp2',
    name: 'Ruz Ma Djaj',
    description: 'Chicken & minced lamb mixed with rice topped with fried almonds served with a yogurt side dish',
    price: 1965,
    category: 'Big Plates',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=80',
    allergens: ['Nuts', 'Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm6', 'vm19', 'vm8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bp3',
    name: 'Kibbeh Bil Laban',
    description: 'Balls of minced lamb in cracked wheat cooked in rice & yogurt with garlic & coriander topped with pine kernels',
    price: 1985,
    category: 'Big Plates',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Nuts'],
    available: true,
    pairedItemIds: ['vm6', 'vm8', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bp4',
    name: 'Sayadieh',
    description: 'Flaked fillets of cod cooked & served on a bed of saffron rice topped with fried onions & tahini sauce',
    price: 1975,
    category: 'Big Plates',
    imageUrl: '/aqua/sayadieh.jpg',
    allergens: ['Fish', 'Sesame'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vm19', 'vm6', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bp5',
    name: 'Strozzapretti',
    description: 'Our famous pasta with chicken & prawns in a creamy red pesto sauce garnished with spring onions',
    price: 1450,
    category: 'Big Plates',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
    allergens: ['Gluten', 'Crustaceans', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['vm17', 'vm6', 'sd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === MEZZA PLATTERS ===
  {
    id: 'pl1',
    name: 'Mezza Starter',
    description: 'Per person — minimum 2 people. Hommous, moutabel, tabboulleh, falafel, batata harra, warak enab, kibbeh & sambousek',
    price: 1399,
    category: 'Mezza Platters',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    allergens: ['Sesame', 'Gluten', 'Nuts'],
    available: true,
    pairedItemIds: ['pl2', 'mm1', 'mm2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pl2',
    name: 'Full Mezza for 2',
    description: 'Hommous, moutabel, tabboulleh, falafel, sujuk, batata harra, warak enab, kibbeh & sambousek — followed by mixed grill & moussaka, baklawa & mint tea',
    price: 6895,
    category: 'Mezza Platters',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    allergens: ['Sesame', 'Gluten', 'Nuts', 'Milk'],
    available: true,
    pairedItemIds: ['pl3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pl3',
    name: 'Full Mezza for 4',
    description: 'Hommous, moutabel, tabboulleh, falafel, sujuk, batata harra, warak enab, kibbeh & sambousek — followed by mixed grill & moussaka, baklawa & mint tea',
    price: 13790,
    category: 'Mezza Platters',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    allergens: ['Sesame', 'Gluten', 'Nuts', 'Milk'],
    available: true,
    pairedItemIds: ['pl2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === WORLD OF WINGS ===
  {
    id: 'ww1',
    name: 'Wings — Lebanon',
    description: 'x8 crispy wings: garlic, lemon, olive oil — uncoated & grilled',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww2',
    name: 'Wings — New York',
    description: 'x8 crispy wings: hot buffalo sauce & blue cheese dressing',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww3',
    name: 'Wings — London',
    description: 'x8 wings: our crunchy buttermilk coated wings',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww4',
    name: 'Wings — Tennessee',
    description: 'x8 crispy wings: red hot chilli & garlic sauce',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd11'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww5',
    name: 'Wings — Oklahoma',
    description: 'x8 crispy wings: signature smoked BBQ sauce',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['sd4', 'sd5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww6',
    name: 'Wings — Seoul',
    description: 'x8 crispy wings: sweet, sour & spicy Gochujang sauce',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: ['Gluten', 'Soya'],
    available: true,
    pairedItemIds: ['sd4', 'sd5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww7',
    name: 'Wings — Brazil',
    description: 'x8 crispy wings: mango periperi sauce',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['sd4', 'sd5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ww8',
    name: 'Wings — Kyiv',
    description: 'x8 wings: crunchy buttermilk with garlic & parsley',
    price: 750,
    category: 'World of Wings',
    imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === WORLD OF BURGERS ===
  {
    id: 'wb1',
    name: 'Beirut Burger',
    description: 'Premium lamb smashed with cheese, coleslaw, fries and sauce in bun served with garlic fries on the side',
    price: 1300,
    category: 'World of Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wb2',
    name: 'Basic Chick',
    description: '2 crispy fried tenders with mayo and crunchy lettuce, served in our classic brioche',
    price: 645,
    category: 'World of Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Eggs'],
    available: true,
    pairedItemIds: ['sd4', 'sd5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wb3',
    name: 'Absurd BBQ Chicken',
    description: 'Crispy breast fillet with awesome smoked hickory BBQ sauce, mayo, lettuce, tomato and coleslaw',
    price: 985,
    category: 'World of Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Eggs'],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wb4',
    name: 'Madbird Buffalo',
    description: 'Crispy breast fillet with a Buffalo sauce, carrot slaw, blue cheese dressing, mayo, lettuce and tomato',
    price: 995,
    category: 'World of Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['sd4', 'sd5', 'sd6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wb5',
    name: 'Nashville Hot',
    description: 'Crispy breast fillet with our Nashville hot sauce, lettuce, tomato, chipotle mayo, pickles and a crispy onion ring',
    price: 995,
    category: 'World of Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Eggs'],
    available: true,
    pairedItemIds: ['sd4', 'sd8', 'sd11'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wb6',
    name: 'Spicy Korean BBQ',
    description: 'Crispy breast fillet with a sweet & hot Korean BBQ sauce, kimchi, pickles, spicy mayo and a crispy onion ring',
    price: 1095,
    category: 'World of Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Soya'],
    available: true,
    pairedItemIds: ['sd4', 'sd8'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === VEGAN BURGERS ===
  {
    id: 'vb1',
    name: 'The Virdy',
    description: 'Vird Fillet, Lettuce, Mayo',
    price: 695,
    category: 'Vegan Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd4', 'sd7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vb2',
    name: 'BBQ Vird',
    description: 'Vird Fillet, BBQ Sauce, Crispy Onions, Coleslaw, Lettuce, Tomato, Mayo',
    price: 950,
    category: 'Vegan Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd4', 'sd7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vb3',
    name: 'The Frankie',
    description: 'Vird Fillet, Buffalo Sauce, Sheese Slice, Carrot Slaw, Lettuce, Tomato, Mayo',
    price: 975,
    category: 'Vegan Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd4', 'sd8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vb4',
    name: 'The Vruce Lee',
    description: 'Vird Fillet, Korean BBQ Sauce, Kimchi, Gherkins, Crispy Onions, Chipotle Mayo',
    price: 995,
    category: 'Vegan Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    allergens: ['Gluten', 'Soya'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd4', 'sd7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vb5',
    name: 'HOT TO HANDLE',
    description: 'Vird Fillet, Hot Sauce, Onion Ring, Gherkins, Lettuce, Tomato, Chipotle Mayo',
    price: 1045,
    category: 'Vegan Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd4', 'sd7'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // === SIDES ===
  {
    id: 'sd1',
    name: 'Rice',
    description: 'Fluffy steamed rice',
    price: 345,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['mm1', 'mm2', 'mm3', 'bp1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd2',
    name: 'Lamb Fried Rice',
    description: 'Fragrant rice fried with seasoned lamb',
    price: 450,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&q=80',
    allergens: [],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['bp1', 'mm1', 'mm5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd3',
    name: 'Khobez Bread',
    description: 'Warm Lebanese flatbread',
    price: 200,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vm1', 'vm2', 'vm3', 'vm4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd4',
    name: 'Fries',
    description: 'Classic crispy fries',
    price: 345,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['wb1', 'wb2', 'wb3', 'ww1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd5',
    name: 'Garlic Fries',
    description: 'Fries tossed in garlic',
    price: 450,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['wb1', 'ww1', 'wb4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd6',
    name: 'Cheesy Fries with Crispy Onion',
    description: 'Fries loaded with melted cheese and crispy onions',
    price: 600,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['wb1', 'wb4', 'ww2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd7',
    name: 'Chilli Coriander Fries',
    description: 'Fries with chilli and fresh coriander',
    price: 600,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['vb1', 'vb2', 'ww4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd8',
    name: 'Sweet Potato Fries',
    description: 'Crispy sweet potato fries',
    price: 450,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['wb5', 'vb3', 'wb6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd9',
    name: 'Smoky Tater Tots',
    description: 'Crispy smoked tater tots',
    price: 395,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['wb3', 'wb5', 'ww5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd10',
    name: 'Garlic Sauce',
    description: 'Creamy Lebanese garlic sauce',
    price: 120,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['ww1', 'mm2', 'mm4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd11',
    name: 'Chilli Sauce',
    description: 'Hot chilli sauce',
    price: 130,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['ww4', 'mm3', 'wb5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
