import type { MenuItem } from '../../src/types';

const NOW = Date.now();

export const menuItems: MenuItem[] = [

  // ── THAI STARTERS ────────────────────────────────────────────────────────

  {
    id: 'ts1',
    name: 'Satay Chicken',
    description: 'Grilled marinated strips of chicken breast in herbs and spices, served with a rich peanut dipping sauce.',
    price: 695,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800&auto=format&fit=crop&q=80',
    allergens: ['Peanuts'],
    available: true,
    pairedItemIds: ['tc1', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts2',
    name: 'Ped Ron: Crispy Duck',
    description: 'Aromatic crispy duck served with pancakes, cucumber, spring onion and hoi sin sauce. A must try.',
    price: 795,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1580554430120-5a2abb2d3c4d?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['tc4', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts3',
    name: 'Tempura Butterfly Prawns',
    description: 'King prawns battered in Thai breadcrumb, served with sweet chilli dipping sauce.',
    price: 750,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Crustaceans'],
    available: true,
    pairedItemIds: ['tc6', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts4',
    name: 'Fish Cake',
    description: 'Marinated feather-back fish paste blended with fresh Thai herbs and spices, served with sweet chilli sauce.',
    price: 650,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish', 'Eggs'],
    available: true,
    pairedItemIds: ['tsp1', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts5',
    name: 'Sesame Prawns on Toast',
    description: 'Deep fried minced prawns on toast coated in sesame seeds, served with sweet chilli sauce.',
    price: 650,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Sesame', 'Gluten', 'Crustaceans'],
    available: true,
    pairedItemIds: ['tg5', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts6',
    name: 'Hoy Obb: Steamed Scallops',
    description: 'Steamed scallops with spicy Thai sauce and fresh coriander.',
    price: 795,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Molluscs'],
    available: true,
    pairedItemIds: ['tsp5', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts7',
    name: 'Goong Ta Lai: Steamed Prawns',
    description: 'Steamed tiger prawns served with a special homemade spicy dipping sauce.',
    price: 850,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans'],
    available: true,
    pairedItemIds: ['tc6', 'nr7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts8',
    name: 'Goong Paow: Grilled Prawns',
    description: 'Grilled marinated king prawns served with a spicy lemon and garlic sauce. Must try.',
    price: 1095,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans'],
    available: true,
    pairedItemIds: ['tc2', 'nr7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts9',
    name: 'Goong Hom Sabai: Prawn Spring Rolls',
    description: 'Deep fried tiger prawns wrapped in crisp pastry, served with sweet chilli sauce.',
    price: 650,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Crustaceans'],
    available: true,
    pairedItemIds: ['sf2', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts10',
    name: 'Blue Orchid Platter',
    description: 'A selection of Thai mixed starters: Chicken Satay, Fish Cake, Spring Roll and Prawn Toast, served with various dips and sauces. Per person.',
    price: 895,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Peanuts', 'Fish', 'Crustaceans', 'Sesame'],
    available: true,
    pairedItemIds: ['tc3', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts11',
    name: 'Phak Tord: Battered Vegetables',
    description: 'Deep fried crispy battered mixed vegetables, served with sweet chilli sauce.',
    price: 595,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['veg3', 'tc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts12',
    name: 'Tord Mun Kao Phod: Sweetcorn Fritters',
    description: 'Deep fried sweetcorn fritters served with sweet chilli sauce.',
    price: 595,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['tc4', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts13',
    name: 'Vegetable Spring Rolls',
    description: 'Thai vegetarian spring rolls stuffed with mixed vegetables and glass noodles, served with sweet chilli sauce.',
    price: 595,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1607330289024-1535c6b4e1c1?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Soya'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['tc1', 'veg3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ts14',
    name: 'Vegetarian Platter',
    description: 'A selection of mixed vegetable starters served with various dips and sauces. Per person.',
    price: 795,
    category: 'thai-starters',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['tc4', 'nr7'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SOUPS ─────────────────────────────────────────────────────────────────

  {
    id: 'so1',
    name: 'Tom Yum Soup: Chicken',
    description: 'Traditional Thai spicy and sour soup with lemongrass, mushrooms, kaffir lime leaves, galangal and chilli oil paste. Also available with Tiger Prawns (£8.95), Mixed Seafood (£9.95) or Mushroom-V (£6.95).',
    price: 795,
    category: 'soups',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['tc1', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'so2',
    name: 'Tom Kha Soup: Chicken',
    description: 'Traditional sour and spicy soup with Thai herbs, mushrooms and lemongrass in creamy coconut milk. Also available with Tiger Prawns (£8.95), Mixed Seafood (£9.95) or Mushroom-V (£6.95).',
    price: 795,
    category: 'soups',
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['tc3', 'nr7'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SALADS ────────────────────────────────────────────────────────────────

  {
    id: 'sa1',
    name: 'Som Tom: Thai Papaya Salad',
    description: 'Spicy shredded papaya with carrot, crushed peanuts, tomato, garlic and fresh lime juice. Must try.',
    price: 895,
    category: 'salads',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80',
    allergens: ['Peanuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['tg1', 'nr8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sa2',
    name: 'Yum Talay: Seafood Salad',
    description: 'Spicy mixed seafood topped with fresh Thai herbs in a tangy spicy dressing.',
    price: 1150,
    category: 'salads',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans', 'Fish', 'Molluscs'],
    available: true,
    pairedItemIds: ['tg6', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sa3',
    name: 'Yam Neau Yang: Beef Salad',
    description: 'Marinated grilled beef (or crispy duck) topped with fresh Thai herbs and a spicy lime dressing.',
    price: 1050,
    category: 'salads',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['tg2', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sa4',
    name: 'Phla Goong: Prawn & Lemongrass Salad',
    description: 'Spicy tiger prawns with fresh lemongrass and kaffir lime leaves in a sour chilli oil sauce.',
    price: 1050,
    category: 'salads',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans', 'Milk'],
    available: true,
    pairedItemIds: ['tsp3', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sa5',
    name: 'Lab Gai: Minced Chicken Salad',
    description: 'Traditional minced chicken salad with a special Thai herb dressing.',
    price: 1050,
    category: 'salads',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['tg1', 'nr8'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── THAI CURRIES ─────────────────────────────────────────────────────────
  // All curries: Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable with Tofu £10.95

  {
    id: 'tc1',
    name: 'Green Curry',
    description: 'Classic Thai green curry with coconut milk, aubergine, bamboo shoot, fine beans, mixed pepper and fresh Thai basil. Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable £10.95.',
    price: 1195,
    category: 'thai-curries',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['nr6', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tc2',
    name: 'Red Curry',
    description: 'Classic Thai red curry with coconut milk, aubergine, bamboo shoot, fine beans, mixed pepper and fresh Thai basil. Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable £10.95.',
    price: 1195,
    category: 'thai-curries',
    imageUrl: 'https://images.unsplash.com/photo-1604520044771-6a5285ff9b73?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['nr6', 'ts1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tc3',
    name: 'Mussaman Curry',
    description: 'A rich, popular southern Thai curry cooked in coconut milk with potatoes, onion and peanut. Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable £10.95.',
    price: 1195,
    category: 'thai-curries',
    imageUrl: '/blue-orchid/massaman-curry.jpg',
    allergens: ['Peanuts'],
    available: true,
    pairedItemIds: ['nr7', 'so2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tc4',
    name: 'Yellow Curry',
    description: 'A mild, romantic curry cooked in coconut milk with potato and onion. Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable £10.95.',
    price: 1195,
    category: 'thai-curries',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['nr6', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tc5',
    name: 'Geang Pa: Jungle Curry',
    description: 'Very spicy Thai jungle curry with no coconut milk, cooked with bamboo shoot, aubergine, mixed pepper, baby corn, fine beans and chilli. Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable £10.95.',
    price: 1195,
    category: 'thai-curries',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['nr6', 'veg3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tc6',
    name: 'Panang Curry',
    description: 'A rich, aromatic curry cooked in coconut milk, topped with long red chilli and kaffir lime leaves. Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable £10.95.',
    price: 1195,
    category: 'thai-curries',
    imageUrl: 'https://images.unsplash.com/photo-1604520044771-6a5285ff9b73?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['nr7', 'veg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── STIR FRIED ───────────────────────────────────────────────────────────
  // All stir fries: Chicken £11.95 · Beef/Lamb £13.95 · Duck £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Seabass £18.95 · Vegetable with Tofu £10.95

  {
    id: 'sf1',
    name: 'Phad Peaw Wan: Sweet & Sour',
    description: 'Light Thai-style stir fry with mixed vegetables in a sweet and sour sauce. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Soya'],
    available: true,
    pairedItemIds: ['nr6', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf2',
    name: 'Phad Graprao: Chilli & Basil',
    description: 'Stir fried with garlic, fresh chillies and fragrant Thai basil in oyster sauce. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Molluscs', 'Soya'],
    available: true,
    pairedItemIds: ['nr5', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf3',
    name: 'Pad Nam Prik Pao',
    description: 'Must try. Stir fried with chilli paste, onion, carrot, mixed pepper, fine beans, baby corn, spring onion and sweet basil. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Soya', 'Milk'],
    available: true,
    pairedItemIds: ['nr6', 'sa1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf4',
    name: 'Phad Khing: Stir Fried Ginger',
    description: 'Stir fried with fresh ginger, spring onions and black fungus mushrooms in soya bean paste. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Soya'],
    available: true,
    pairedItemIds: ['nr6', 'so1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf5',
    name: 'Phad Num-Mun Hoy: Oyster Sauce',
    description: 'Stir fried with mushroom, spring onion, peppers and oyster sauce. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Molluscs', 'Soya'],
    available: true,
    pairedItemIds: ['nr6', 'veg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf6',
    name: 'Phad Med Ma Muang: Cashew Nuts',
    description: 'Stir fried with roasted chillies, crunchy cashew nuts and chilli oil. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Nuts', 'Soya'],
    available: true,
    pairedItemIds: ['nr6', 'veg3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf7',
    name: 'Phad Gra Tium Prik Thai: Garlic & Black Pepper',
    description: 'Sautéed with black pepper and garlic sauce. Chicken £11.95 · Beef/Lamb £13.95 · Tiger Prawn £14.95 · King Prawn £17.95 · Vegetable £10.95.',
    price: 1195,
    category: 'stir-fried',
    imageUrl: '/blue-orchid/pad-nam-prik-pao.jpg',
    allergens: ['Soya'],
    available: true,
    pairedItemIds: ['nr6', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── THAI GRILL / SIZZLING ────────────────────────────────────────────────

  {
    id: 'tg1',
    name: 'Gai Yang: Grilled Chicken',
    description: 'Chargrilled Thai-style marinated chicken served with a tangy Thai chilli sauce.',
    price: 1495,
    category: 'thai-grill',
    imageUrl: 'https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['sa1', 'nr8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tg2',
    name: 'Seau Rong Hai: Grilled Sirloin Steak',
    description: 'Grilled beef sirloin steak with special Thai chilli sauce, served with broccoli, carrots and cauliflower.',
    price: 1595,
    category: 'thai-grill',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['sa3', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tg3',
    name: 'Ped Yang: Grilled Duck',
    description: 'Grilled marinated duck breast glazed with soya sauce.',
    price: 1595,
    category: 'thai-grill',
    imageUrl: 'https://images.unsplash.com/photo-1580554430120-5a2abb2d3c4d?w=800&auto=format&fit=crop&q=80',
    allergens: ['Soya'],
    available: true,
    pairedItemIds: ['tsp4', 'nr7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tg4',
    name: 'Gae Yang: Thai Lamb Chops',
    description: 'Thai-style lamb chops with peppers and garlic, char-grilled to perfection.',
    price: 1695,
    category: 'thai-grill',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['sa5', 'nr8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tg5',
    name: 'Goong Paow: Grilled King Prawns',
    description: 'Must try. Grilled jumbo king prawns served with a spicy lemon and garlic sauce.',
    price: 1795,
    category: 'thai-grill',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans'],
    available: true,
    pairedItemIds: ['sa4', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tg6',
    name: 'Pla Yang: Grilled Seabass in Banana Leaf',
    description: 'Whole seabass wrapped in exotic banana leaf, garnished with Thai herbs and grilled over charcoal.',
    price: 1795,
    category: 'thai-grill',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish'],
    available: true,
    pairedItemIds: ['sa1', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── THAI CHEF'S SPECIALS ──────────────────────────────────────────────────

  {
    id: 'tsp1',
    name: 'Pla Neung Ma: Spicy Steamed Sea Bass',
    description: 'Steamed fresh sea bass topped with spicy lemon dressing and aromatic Thai herbs.',
    price: 1795,
    category: 'thai-specials',
    imageUrl: '/blue-orchid/lime-ginger-sea-bass.jpg',
    allergens: ['Fish'],
    available: true,
    pairedItemIds: ['sa2', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tsp2',
    name: 'Pla Neung Se-Eaw: Steamed Sea Bass with Ginger',
    description: 'Steamed whole sea bass topped with fresh ginger, spring onions and soya sauce. A gentle, fragrant dish.',
    price: 1795,
    category: 'thai-specials',
    imageUrl: '/blue-orchid/lime-ginger-sea-bass.jpg',
    allergens: ['Fish', 'Soya'],
    available: true,
    pairedItemIds: ['nr6', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tsp3',
    name: 'Chu Chee Goong: King Prawns',
    description: 'Jumbo king prawns in a smooth aromatic red curry sauce with kaffir lime leaves.',
    price: 1795,
    category: 'thai-specials',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans'],
    available: true,
    pairedItemIds: ['nr7', 'veg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tsp4',
    name: 'Ped Ma Kham: Duck Tamarind',
    description: 'Must try. Roasted duck breast served with a smooth, rich tamarind sauce.',
    price: 1695,
    category: 'thai-specials',
    imageUrl: 'https://images.unsplash.com/photo-1580554430120-5a2abb2d3c4d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['nr7', 'veg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tsp5',
    name: 'Hoy Shell Phad Bai Gra Paow: Holy Basil Scallops',
    description: 'Sea scallops stir fried with garlic, fresh chillies and fragrant holy basil leaves.',
    price: 1595,
    category: 'thai-specials',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Molluscs'],
    available: true,
    pairedItemIds: ['nr6', 'veg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tsp6',
    name: 'Hoy Shell Pad Prik Thai Dum: Black Pepper Scallops',
    description: 'Flash-fried sea scallops with black pepper and garlic.',
    price: 1595,
    category: 'thai-specials',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Molluscs'],
    available: true,
    pairedItemIds: ['nr6', 'sa4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'tsp7',
    name: 'Rum-Mit Talay Paow: Spicy Mixed Seafood',
    description: 'Must try. Mixed grilled seafood — king prawns, squid, green mussels and scallops — served with a Thai spicy chilli oil sauce.',
    price: 2595,
    category: 'thai-specials',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans', 'Molluscs'],
    available: true,
    pairedItemIds: ['nr6', 'sa2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── VEGETABLES ───────────────────────────────────────────────────────────

  {
    id: 'veg1',
    name: 'Pad Pak Choi',
    description: 'Stir-fried pak choi with oyster sauce and garlic. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: ['Molluscs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['tc1', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'veg2',
    name: 'Hed Gratiem: Garlic Mushrooms',
    description: 'Stir fried seasonal mushrooms with garlic and black pepper. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sf7', 'nr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'veg3',
    name: 'Pad Pak Ruam Mit: Mixed Vegetables',
    description: 'Stir fried assorted vegetables with garlic, chillies and soy sauce. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: ['Soya'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['tc4', 'nr5'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── NOODLES & RICE ────────────────────────────────────────────────────────

  {
    id: 'nr1',
    name: 'Pad Thai: Chicken',
    description: 'Stir fried rice noodles with egg, carrot, spring onion, beansprouts and tamarind sauce. Also available with Seafood (£15.95), Tiger Prawn (£14.95) or Vegetable with Tofu (£10.95).',
    price: 1295,
    category: 'noodles-rice',
    imageUrl: '/blue-orchid/pad-thai.jpg',
    allergens: ['Gluten', 'Eggs', 'Soya'],
    available: true,
    pairedItemIds: ['ts1', 'tc2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr2',
    name: 'Pad Sea-Eaw Noodles: Chicken',
    description: 'Stir fried flat rice noodles with egg, vegetables and soy sauce. Also available with Seafood (£15.95), Tiger Prawn (£14.95) or Vegetable with Tofu (£10.95).',
    price: 1295,
    category: 'noodles-rice',
    imageUrl: '/blue-orchid/pad-thai-noodle.jpg',
    allergens: ['Gluten', 'Eggs', 'Soya'],
    available: true,
    pairedItemIds: ['sf2', 'ts9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr3',
    name: 'Khao Pad Sabparod: Pineapple Fried Rice',
    description: 'Stir fried Thai jasmine rice with cashew nuts and pineapple. Also available with Chicken, Seafood, Tiger Prawn or Vegetable.',
    price: 1295,
    category: 'noodles-rice',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: ['Nuts', 'Eggs', 'Soya'],
    available: true,
    pairedItemIds: ['tc6', 'tg5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr4',
    name: 'Blue Orchid Fried Rice: Chicken',
    description: 'Stir fried rice with egg, tomato, onion and spring onions. Also available with Seafood (£15.95), Tiger Prawn (£14.95) or Vegetable with Tofu (£10.95).',
    price: 1295,
    category: 'noodles-rice',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: ['Eggs', 'Soya'],
    available: true,
    pairedItemIds: ['tc1', 'ts1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr5',
    name: 'Thai Egg Fried Rice',
    description: 'Lightly seasoned Thai jasmine rice stir fried with egg.',
    price: 395,
    category: 'noodles-rice',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: ['Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sf3', 'tc2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr6',
    name: 'Thai Jasmine Rice',
    description: 'Steamed fragrant Thai jasmine rice.',
    price: 395,
    category: 'noodles-rice',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['tc3', 'tsp3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr7',
    name: 'Thai Coconut Rice',
    description: 'Fragrant rice cooked in coconut milk.',
    price: 395,
    category: 'noodles-rice',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['tsp4', 'tg3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr8',
    name: 'Thai Sticky Rice',
    description: 'Traditional glutinous sticky rice, steamed in the Thai style.',
    price: 395,
    category: 'noodles-rice',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['tg1', 'sa1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'nr9',
    name: 'Plain Noodles',
    description: 'Plain steamed rice noodles.',
    price: 495,
    category: 'noodles-rice',
    imageUrl: '/blue-orchid/pad-thai-noodle.jpg',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sf1', 'tc5'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── INDIAN STARTERS ───────────────────────────────────────────────────────

  {
    id: 'is1',
    name: 'Onion Bhaji',
    description: 'Crispy golden onion fritters seasoned with spices, served with mint chutney.',
    price: 450,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['im1', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is2',
    name: 'Samosa',
    description: 'Crisp pastry parcels filled with your choice of Chicken, Lamb or Vegetable filling.',
    price: 450,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['im5', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is3',
    name: 'Pakora: Chicken or Lamb',
    description: 'Tender pieces of chicken or lamb in a spiced gram flour batter, deep fried until golden.',
    price: 550,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['im6', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is4',
    name: 'Sheek / Shami Kebab',
    description: 'Minced lamb or chicken kebab with fresh herbs and spices, cooked on the grill.',
    price: 550,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['im4', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is5',
    name: 'Tikka: Chicken or Lamb',
    description: 'Marinated pieces of chicken or lamb roasted in the clay oven.',
    price: 550,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['isp1', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is6',
    name: 'Garlic Chicken Tikka',
    description: 'Chicken tikka marinated with garlic and spices, roasted in the clay oven.',
    price: 550,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['im1', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is7',
    name: 'Spicy Wings',
    description: 'Must try. Spiced chicken wings marinated and grilled to juicy perfection.',
    price: 595,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['im6', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is8',
    name: 'Lamb Chops (3 pcs)',
    description: 'Lamb chops marinated in homemade spiced sauce overnight, then cooked in the tandoor.',
    price: 695,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['im4', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is9',
    name: 'Tandoori King Prawn',
    description: 'King prawns marinated in spices and roasted in the clay oven.',
    price: 695,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans'],
    available: true,
    pairedItemIds: ['iseaf1', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is10',
    name: 'Paneer Tikka',
    description: 'Indian cheese marinated in herbs and spices, roasted in the clay oven.',
    price: 550,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['iveg4', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is11',
    name: 'Tetul Mix',
    description: 'Must try. Succulent lamb and chicken tikka with mushrooms, crunchy onions and capsicum pan fried in tangy tamarind sauce, served with a paratha.',
    price: 650,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['im2', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is12',
    name: 'Indian Mix Platter',
    description: 'Mixture of Chicken, Lamb and King Prawn Tikka, Vegetable Samosa, Sheek Kebab and Onion Bhaji. Per person.',
    price: 895,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Crustaceans'],
    available: true,
    pairedItemIds: ['isp1', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is13',
    name: 'Tandoori Chicken (Half)',
    description: 'Marinated on-the-bone chicken roasted in the clay oven — a classic Indian grill.',
    price: 1095,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['isp6', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is14',
    name: 'Lamb Chops (6 pcs)',
    description: 'Six lamb chops marinated in homemade spiced sauce overnight, cooked in the tandoor.',
    price: 1395,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['im4', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'is15',
    name: 'Seafood Mix Grill',
    description: 'Fish tikka, king prawn, scallop and fish kebab served on a sizzler.',
    price: 1795,
    category: 'indian-starters',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish', 'Crustaceans', 'Molluscs'],
    available: true,
    pairedItemIds: ['iseaf1', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── INDIAN MAINS (Favourites) ─────────────────────────────────────────────
  // Each sauce available in: Chicken £9.95 · Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95

  {
    id: 'im1',
    name: 'Masala / Balti',
    description: 'Aromatic tomato-based curry with a rich masala sauce. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/bhuna.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid2', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im2',
    name: 'Bhuna',
    description: 'A dry, thick sauce cooked with onions, tomatoes and spices. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/bhuna.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid2', 'sid9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im3',
    name: 'Pathia',
    description: 'A hot, sweet and sour curry with a tangy tomato base. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/chicken-jalfrezi.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid2', 'sid9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im4',
    name: 'Rogon / Sagwala',
    description: 'Rogon Josh with a rich tomato and red pepper sauce, or Sagwala with fresh spinach. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/rogon-josh.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid2', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im5',
    name: 'Kurma / Pasanda',
    description: 'Mild, creamy curry with a coconut and almond sauce. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk', 'Nuts'],
    available: true,
    pairedItemIds: ['sid3', 'sid7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im6',
    name: 'Madras',
    description: 'A hot, spicy curry with a tangy sauce. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/chicken-jalfrezi.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid2', 'sid9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im7',
    name: 'Vindaloo',
    description: 'Very hot and fiery curry — not for the faint hearted! Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/chicken-jalfrezi.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid8', 'sid9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'im8',
    name: 'Dansak / Dupiaza',
    description: 'Dansak — sweet, sour and hot with lentils. Dupiaza — with two types of onion. Chicken or Prawn £9.95 · Lamb £10.95 · King Prawn £15.95 · Vegetable £8.95 · Paneer £9.95.',
    price: 995,
    category: 'indian-mains',
    imageUrl: '/blue-orchid/bhuna.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── INDIAN CHEF'S SPECIALS ────────────────────────────────────────────────

  {
    id: 'isp1',
    name: 'Butter Chicken',
    description: 'A Calcutta classic. Boneless marinated chicken in a delicious buttery mild sauce of ground almond, crushed ginger, yoghurt and mango chutney.',
    price: 1195,
    category: 'indian-specials',
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk', 'Nuts'],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp2',
    name: 'Tamil Garlic',
    description: 'Must try. Chicken, Lamb and Grilled King Prawn in a deeply aromatic roasted garlic sauce.',
    price: 1195,
    category: 'indian-specials',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk', 'Crustaceans'],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp3',
    name: 'Jalfrezi: Chicken or Lamb',
    description: 'A hot, vibrant pepper and onion-based sauce. Spicy and full of flavour.',
    price: 1195,
    category: 'indian-specials',
    imageUrl: '/blue-orchid/chicken-jalfrezi.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid2', 'sid9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp4',
    name: 'Shashlik Bhuna: Chicken or Lamb',
    description: 'Marinated tikka with onions, tomatoes and capsicum cooked in a clay oven, then served in a rich bhuna sauce.',
    price: 1295,
    category: 'indian-specials',
    imageUrl: '/blue-orchid/bhuna.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid7', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp5',
    name: 'Northern Bengal Garlic Chilli: Chicken or Lamb',
    description: 'Bengali style chicken or lamb fried in garlic and onions, cooked in a spicy sauce for a rich, hot flavour.',
    price: 1195,
    category: 'indian-specials',
    imageUrl: '/blue-orchid/chicken-jalfrezi.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp6',
    name: 'Gujarat Chicken',
    description: 'Must try. On-the-bone tandoori chicken cooked with onions, green pepper and dry chilli seed in a lightly dry, fairly hot sauce. Served with pilau rice.',
    price: 1595,
    category: 'indian-specials',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['iveg2', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp7',
    name: 'Murgi Masala',
    description: 'Garden peas and minced meat with tandoori chicken off the bone, cooked with a boiled egg.',
    price: 1395,
    category: 'indian-specials',
    imageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'isp8',
    name: 'Combination Dish',
    description: 'Sample two dishes in small portions. Choose any pair: Chicken Jalfrezi & Lamb Sagwala · Chicken Tikka Masala & Lamb Bhuna · Chicken Bhuna & Prawn Pathia · Chicken Chilli Bhuna & Lamb Pathia.',
    price: 1395,
    category: 'indian-specials',
    imageUrl: '/blue-orchid/combination-dish.jpg',
    allergens: [],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── INDIAN SEAFOOD SPECIAL ────────────────────────────────────────────────

  {
    id: 'iseaf1',
    name: 'Seafood Lazeez',
    description: 'Must try. Scallop, salmon and king prawns pan-fried with cardamom, fresh lemon, coriander, tomatoes, ginger, fresh methi and lime juice in a spicy medium sauce.',
    price: 1695,
    category: 'indian-seafood',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish', 'Crustaceans', 'Molluscs', 'Milk'],
    available: true,
    pairedItemIds: ['sid7', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iseaf2',
    name: 'Lime & Ginger Sea Bass',
    description: 'Pan fried fillet of seabass on a bed of sautéed spinach and red pepper, with cumin new potatoes, drizzled with vine cherry tomato and fish broth.',
    price: 1695,
    category: 'indian-seafood',
    imageUrl: '/blue-orchid/lime-ginger-sea-bass.jpg',
    allergens: ['Fish'],
    available: true,
    pairedItemIds: ['iveg2', 'sid9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iseaf3',
    name: 'Malaysian Spicy King Prawn',
    description: 'Must try. King prawns simmered in coconut milk, lemongrass, red chillies and mustard with cucumber and mango.',
    price: 1795,
    category: 'indian-seafood',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans', 'Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sid7', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iseaf4',
    name: 'Salmon Tikka ke Masala',
    description: 'Pink salmon marinated in spices and lime juice with fresh herbs, roasted in the oven then smothered in a smooth, creamy masala sauce.',
    price: 1695,
    category: 'indian-seafood',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish', 'Milk'],
    available: true,
    pairedItemIds: ['sid7', 'sid2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── BIRYANI ───────────────────────────────────────────────────────────────

  {
    id: 'bir1',
    name: 'House Special Biryani',
    description: 'Fragrant basmati rice cooked with a medley of meats and aromatic spices. Served with biryani sauce.',
    price: 1395,
    category: 'biryani',
    imageUrl: '/blue-orchid/house-special-biryani.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid9', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bir2',
    name: 'Chicken / Lamb Tikka Biryani',
    description: 'Fragrant basmati rice layered with tender chicken or lamb tikka. Served with biryani sauce.',
    price: 1195,
    category: 'biryani',
    imageUrl: '/blue-orchid/desi-biryani.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid9', 'iveg4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bir3',
    name: 'King Prawn Biryani',
    description: 'Fragrant basmati rice with succulent king prawns and aromatic spices. Served with biryani sauce.',
    price: 1495,
    category: 'biryani',
    imageUrl: '/blue-orchid/desi-biryani.jpg',
    allergens: ['Crustaceans', 'Milk'],
    available: true,
    pairedItemIds: ['sid9', 'iveg5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bir4',
    name: 'Chicken / Lamb / Prawn Biryani',
    description: 'Classic desi biryani with your choice of chicken, lamb or prawn. Served with biryani sauce.',
    price: 1095,
    category: 'biryani',
    imageUrl: '/blue-orchid/desi-biryani.jpg',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sid9', 'iveg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bir5',
    name: 'Vegetable Biryani',
    description: 'Fragrant basmati rice layered with spiced mixed vegetables. Served with biryani sauce.',
    price: 995,
    category: 'biryani',
    imageUrl: '/blue-orchid/desi-biryani.jpg',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sid9', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── INDIAN VEGETABLE DISHES ───────────────────────────────────────────────

  {
    id: 'iveg1',
    name: 'Tarka Dall',
    description: 'Slow-cooked lentils tempered with cumin, garlic and spices. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'indian-veg',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sid2', 'im1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iveg2',
    name: 'Bombay Aloo',
    description: 'Potatoes cooked with tomatoes, onion and aromatic Indian spices. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'indian-veg',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sid2', 'im4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iveg3',
    name: 'Aloo Gobi',
    description: 'Potato and cauliflower cooked with turmeric and spices. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'indian-veg',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sid2', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iveg4',
    name: 'Sag Paneer',
    description: 'Fresh spinach cooked with cubed Indian cheese and spices. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'indian-veg',
    imageUrl: '/blue-orchid/paneer-masala.jpg',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sid2', 'isp1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iveg5',
    name: 'Chana Paneer',
    description: 'Chickpeas and Indian cheese cooked in a spiced tomato sauce. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'indian-veg',
    imageUrl: '/blue-orchid/paneer-masala.jpg',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sid2', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'iveg6',
    name: 'Brinjal Bhaji',
    description: 'Aubergine cooked with onions and aromatic spices. Side £5.95 / Main £8.95.',
    price: 895,
    category: 'indian-veg',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['sid6', 'im2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SIDES (Breads & Indian Rice) ──────────────────────────────────────────

  {
    id: 'sid1',
    name: 'Plain Naan',
    description: 'Soft, fluffy clay oven-baked naan bread.',
    price: 350,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['im1', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid2',
    name: 'Garlic Naan',
    description: 'Naan bread topped with garlic and butter.',
    price: 350,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['isp1', 'iveg4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid3',
    name: 'Peshwari Naan',
    description: 'Sweet naan bread filled with coconut, almond and sultanas.',
    price: 350,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Nuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['im5', 'isp1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid4',
    name: 'Keema Naan',
    description: 'Naan bread stuffed with spiced minced lamb.',
    price: 350,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['im6', 'im4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid5',
    name: 'Paratha',
    description: 'Flaky, layered Indian flatbread.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['isp4', 'iveg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid6',
    name: 'Chapatti',
    description: 'Traditional thin wholemeal flatbread.',
    price: 150,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['im7', 'iveg3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid7',
    name: 'Pilau Rice',
    description: 'Fragrant basmati rice cooked with whole spices.',
    price: 395,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['isp1', 'im4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid8',
    name: 'Boiled Rice',
    description: 'Plain steamed basmati rice.',
    price: 350,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['tc5', 'im7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid9',
    name: 'Raitha',
    description: 'Cool, creamy yoghurt with cucumber and mint — a perfect cooling side.',
    price: 200,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['im7', 'isp3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sid10',
    name: 'Chips',
    description: 'Classic golden chips.',
    price: 350,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['im7', 'im6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
