import type { MenuItem } from '../../src/types';

const NOW = Date.now();

export const menuItems: MenuItem[] = [
  // ── CHILLED MEZZES ──────────────────────────────────────────────────────
  {
    id: 'cm1',
    name: 'Hummus',
    description: 'Classic chickpea purée with tahini, lemon, olive oil, and garlic. Add sautéed meat +£3.50 or sautéed liver +£2.95.',
    price: 725,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    allergens: ['Sesame', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm1', 'hm4', 'cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm2',
    name: 'Mixed Olives',
    description: 'Mixed olives marinated with herbs.',
    price: 575,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1580913428735-bd3c269d6a82?w=800&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm1', 'cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm3',
    name: 'Olive Tree Special',
    description: 'Feta cheese with mixed peppers, olives, basil, olive oil, and black pepper.',
    price: 795,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1533622597524-a1215e26c0a2?w=800&q=80',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm14', 'hm3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm4',
    name: 'Olive Tree Caprise',
    description: 'Grilled halloumi, roasted aubergine, pomegranate molasses, pesto, and olive oil.',
    price: 795,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800&q=80',
    allergens: ['Milk', 'Nuts', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm14', 'hm3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm5',
    name: 'Russian Salad',
    description: 'Potato, carrot, corn, and gherkin in creamy mayonnaise.',
    price: 725,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    allergens: ['Eggs', 'Mustard', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm6',
    name: 'Tabule',
    description: 'Cracked wheat salad with parsley, mint, celery, spring onions, olive oil, lemon, and pomegranate molasses.',
    price: 725,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    allergens: ['Gluten', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm1', 'cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm7',
    name: 'Cacik',
    description: 'Yogurt with cucumber, mint, dill, and garlic.',
    price: 725,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm1', 'hm1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm8',
    name: 'Beetroot Delight',
    description: 'Beetroot salad with feta cheese, walnuts, and vinaigrette.',
    price: 775,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-5ec6a79120b0?w=800&q=80',
    allergens: ['Milk', 'Nuts', 'Sulphites', 'Mustard'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm9',
    name: 'Smoky Courgette',
    description: 'Smoked courgette served with tahini and garlic yogurt.',
    price: 750,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=800&q=80',
    allergens: ['Sesame', 'Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm10',
    name: "Chef's Roast Pepper & Feta",
    description: 'Roasted red peppers with walnuts and feta cheese, topped with minced lamb.',
    price: 795,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80',
    allergens: ['Milk', 'Nuts', 'Sulphites'],
    available: true,
    pairedItemIds: ['cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm11',
    name: 'Saksuka',
    description: 'Fried aubergines, peppers, and onions in tomato sauce.',
    price: 725,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=800&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm14', 'cm1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm12',
    name: 'Yogurtlu Patlican Ezme',
    description: 'Roasted aubergine with garlic yogurt, red pepper, tahini, and olive oil.',
    price: 725,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80',
    allergens: ['Sesame', 'Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm1', 'cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm13',
    name: 'Antep Ezme',
    description: 'Spicy tomato relish mixed with onion, peppers, parsley, garlic, lemon juice, and pomegranate dressing.',
    price: 750,
    category: 'Chilled Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1533622597524-a1215e26c0a2?w=800&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['cm1', 'cm14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cm14',
    name: 'Mixed Cold Mezze',
    description: "Chef's selection of various cold mezze dishes. Perfect for two.",
    price: 1795,
    category: 'Chilled Mezzes',
    imageUrl: '/olive-tree/olive16.webp',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Sesame', 'Nuts', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm13', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── HOT MEZZES ──────────────────────────────────────────────────────────
  {
    id: 'hm1',
    name: 'Olive Tree Borek',
    description: 'Filo pastry stuffed with minced meat, onion, and mozzarella, served with herb mayo.',
    price: 845,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive4.webp',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['hm13', 'cm1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm2',
    name: 'Garlic Prawns',
    description: 'King prawns cooked with mixed peppers, garlic, butter, and Turkish spices. Shell off option available.',
    price: 945,
    category: 'Hot Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&q=80',
    allergens: ['Crustaceans', 'Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['fs1', 'hm13'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm3',
    name: 'Halloumi',
    description: 'Pan-fried Cypriot cheese with yogurt sauce.',
    price: 845,
    category: 'Hot Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm13', 'cm7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm4',
    name: 'Sigara Borek',
    description: 'Filo pastry rolls with feta cheese and mint.',
    price: 845,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive4.webp',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm13', 'cm1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm5',
    name: 'Falafel',
    description: 'Minced balls of chickpeas, vegetables, and broad beans, with homemade chutney and yogurt sauce. Vegan option available.',
    price: 845,
    category: 'Hot Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    allergens: ['Sesame', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm13', 'vv1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm6',
    name: 'Sucuk',
    description: 'Spicy sausage, pan-fried with Turkish herbs.',
    price: 845,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive6.webp',
    allergens: ['Gluten', 'Sulphites'],
    available: true,
    pairedItemIds: ['hm13'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm7',
    name: "Goat's Cheese",
    description: "Herb and sesame seed-coated goat's cheese with salad, tomato chutney, and yogurt sauce.",
    price: 925,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive5.webp',
    allergens: ['Milk', 'Sesame', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm13'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm8',
    name: 'Lamb Liver',
    description: 'Pan-fried lamb liver with onion, peppers, and Turkish spices.',
    price: 945,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive6.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['hm13'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm9',
    name: 'Mushroom Sauté',
    description: 'Mushrooms with onion, peppers, garlic, tomato sauce, and mozzarella. Vegan option available.',
    price: 925,
    category: 'Hot Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&q=80',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hm13'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm10',
    name: 'Whitebait',
    description: 'Crispy breaded whitebait with salad and tartare sauce.',
    price: 845,
    category: 'Hot Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1519984388953-d2406bc725e1?w=800&q=80',
    allergens: ['Gluten', 'Fish', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['hm13', 'fs2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm11',
    name: 'Kalamar',
    description: 'Breaded calamari, deep-fried, with salad and tartare sauce.',
    price: 925,
    category: 'Hot Mezzes',
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80',
    allergens: ['Gluten', 'Molluscs', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['hm13', 'fs3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm12',
    name: 'Mediterranean Fire Wings',
    description: 'Spicy marinated chicken wings with a kick of chilli.',
    price: 975,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive12.webp',
    allergens: ['Gluten', 'Sulphites'],
    available: true,
    pairedItemIds: ['gr4', 'hm13'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hm13',
    name: 'Mixed Hot Mezze',
    description: 'A sharing plate of four hot mezze classics: Olive Tree Borek, Falafel, Sucuk, and Halloumi. Perfect for two.',
    price: 1945,
    category: 'Hot Mezzes',
    imageUrl: '/olive-tree/olive4.webp',
    allergens: ['Gluten', 'Milk', 'Sesame', 'Sulphites'],
    available: true,
    pairedItemIds: ['cm14', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── CHEF'S SALADS ────────────────────────────────────────────────────────
  {
    id: 'cs1',
    name: 'Chicken Salad',
    description: 'Succulent chicken with mixed salad leaves and creamy salad dressing.',
    price: 1695,
    category: "Chef's Salads",
    imageUrl: '/olive-tree/olive10.webp',
    allergens: ['Eggs', 'Mustard', 'Sulphites'],
    available: true,
    pairedItemIds: ['si1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cs2',
    name: 'Chicken Caesar Salad',
    description: 'Lettuce, Parmesan cheese, croutons, and cucumbers, served with chicken breast.',
    price: 1625,
    category: "Chef's Salads",
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Fish', 'Mustard'],
    available: true,
    pairedItemIds: ['si1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cs3',
    name: 'Halloumi Salad',
    description: 'Mixed salad leaves and chargrilled halloumi with dressing.',
    price: 1595,
    category: "Chef's Salads",
    imageUrl: '/olive-tree/olive10.webp',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['si1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── TRADITIONAL DISHES ───────────────────────────────────────────────────
  {
    id: 'td1',
    name: 'Lamb Guvec',
    description: 'Tender chunks of lamb with fresh tomato, red and green pepper, and garlic, topped with melting mozzarella in a traditional hot clay dish. Served with rice and salad.',
    price: 2175,
    category: 'Traditional Dishes',
    imageUrl: '/olive-tree/olive1.webp',
    allergens: ['Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['td2', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td2',
    name: 'Chicken Guvec',
    description: 'Chunks of chicken with fresh tomato, red and green pepper, and garlic, topped with melting mozzarella in a traditional hot clay dish. Served with rice and salad.',
    price: 2090,
    category: 'Traditional Dishes',
    imageUrl: '/olive-tree/olive17.webp',
    allergens: ['Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['td1', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td3',
    name: 'Ottoman Beef Stew',
    description: 'Prime steak beef in a rich sauce with onions, red peppers, and peanuts, served on a traditional plate. Served with rice and salad.',
    price: 2295,
    category: 'Traditional Dishes',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    allergens: ['Peanuts', 'Sulphites'],
    available: true,
    pairedItemIds: ['si4', 'si5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td4',
    name: 'Topkapi Palace Special',
    description: 'Minced lamb kofte wrapped in fried aubergine slices, topped with Halep sauce on a bed of mashed potatoes. Served with rice and salad.',
    price: 2195,
    category: 'Traditional Dishes',
    imageUrl: '/olive-tree/olive1.webp',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Sulphites'],
    available: true,
    pairedItemIds: ['si3', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td5',
    name: "Emperor's Chicken",
    description: 'Chicken breast in a luxurious sweet creamy sauce with a blend of apricots, roasted mixed nuts, and currants. Served with rice and salad.',
    price: 2095,
    category: 'Traditional Dishes',
    imageUrl: '/olive-tree/olive8.webp',
    allergens: ['Milk', 'Nuts', 'Sulphites'],
    available: true,
    pairedItemIds: ['si4', 'td7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td6',
    name: 'Lamb Moussaka',
    description: 'Fried aubergines, potatoes, carrots, courgettes, onions, and minced lamb, topped with béchamel sauce and melted mozzarella. Served with rice and salad.',
    price: 2095,
    category: 'Traditional Dishes',
    imageUrl: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Sulphites'],
    available: true,
    pairedItemIds: ['si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td7',
    name: 'Halep Chicken',
    description: 'Tender chicken pieces with wild mushrooms, onion, and pepper cooked in a creamy authentic Halep sauce. Served with rice and salad.',
    price: 2090,
    category: 'Traditional Dishes',
    imageUrl: '/olive-tree/olive8.webp',
    allergens: ['Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['td5', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'td8',
    name: 'Lamb Shank',
    description: 'Slow-cooked lamb shank with onions, carrots, green and red peppers in a rich tomato sauce. Served with rice and salad.',
    price: 2495,
    category: 'Traditional Dishes',
    imageUrl: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['si4', 'si5'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── OLIVE TREE WRAPS ─────────────────────────────────────────────────────
  {
    id: 'wr1',
    name: 'Chicken Wrap',
    description: 'Grilled succulent chicken breast with fresh salad and mozzarella, drizzled with our chef\'s special sauce and rolled in flatbread. Served with salad and chips.',
    price: 1975,
    category: 'Olive Tree Wraps',
    imageUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['si1', 'wr3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wr2',
    name: 'Mediterranean Wrap',
    description: 'Homemade hummus with halloumi and falafel, wrapped with salad and finished with chef\'s special dressing in fresh Lavash bread. Served with salad and chips.',
    price: 1975,
    category: 'Olive Tree Wraps',
    imageUrl: '/olive-tree/olive13.webp',
    allergens: ['Gluten', 'Milk', 'Sesame', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['si1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wr3',
    name: 'Adana Wrap',
    description: 'Adana lamb kofte with onion, parsley, and Turkish herbs, rolled in fresh Lavash bread with salad and chef\'s special sauce. Served with salad and chips.',
    price: 1975,
    category: 'Olive Tree Wraps',
    imageUrl: '/olive-tree/olive13.webp',
    allergens: ['Gluten', 'Sulphites'],
    available: true,
    pairedItemIds: ['si1', 'wr1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wr4',
    name: 'Chicken Beyti Wrap',
    description: 'Minced chicken kofte with onion, parsley, and Turkish herbs, rolled in fresh Lavash bread with salad and chef\'s special sauce. Served with salad and chips.',
    price: 1975,
    category: 'Olive Tree Wraps',
    imageUrl: '/olive-tree/olive13.webp',
    allergens: ['Gluten', 'Sulphites'],
    available: true,
    pairedItemIds: ['si1', 'wr1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'wr5',
    name: 'Liver Wrap',
    description: 'Pan-fried lamb liver with onion, peppers, and Turkish spices, rolled in fresh Lavash bread with salad and chef\'s special sauce. Served with salad and chips.',
    price: 1975,
    category: 'Olive Tree Wraps',
    imageUrl: '/olive-tree/olive13.webp',
    allergens: ['Gluten', 'Sulphites'],
    available: true,
    pairedItemIds: ['si1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── FROM THE SEA ─────────────────────────────────────────────────────────
  {
    id: 'fs1',
    name: 'Prawn Guvec',
    description: 'Prawns, peppers, onions, fresh tomato, and garlic cooked in a creamy rich tomato sauce. Served with sautéed potatoes.',
    price: 2095,
    category: 'From the Sea',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80',
    allergens: ['Crustaceans', 'Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['hm2', 'si6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fs2',
    name: 'Levrek',
    description: 'Marinated whole sea bass with sautéed potatoes and salad.',
    price: 2250,
    category: 'From the Sea',
    imageUrl: '/olive-tree/olive11.webp',
    allergens: ['Fish', 'Sulphites'],
    available: true,
    pairedItemIds: ['si6', 'fs3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fs3',
    name: 'Cupra',
    description: 'Marinated whole sea bream with sautéed potatoes and salad.',
    price: 2290,
    category: 'From the Sea',
    imageUrl: '/olive-tree/olive14.webp',
    allergens: ['Fish', 'Sulphites'],
    available: true,
    pairedItemIds: ['si6', 'fs2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'fs4',
    name: 'Salmon',
    description: 'Oven-baked salmon with parsley, lemon juice, and olive oil. Served with sautéed potatoes and salad.',
    price: 2290,
    category: 'From the Sea',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80',
    allergens: ['Fish', 'Sulphites'],
    available: true,
    pairedItemIds: ['si6'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── FROM THE CHARCOAL GRILL ──────────────────────────────────────────────
  {
    id: 'gr1',
    name: 'Adana',
    description: 'Traditional minced lamb kofte with onion, parsley, and a blend of Turkish herbs and spices, cooked over the charcoal grill. Served with rice and salad.',
    price: 1995,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive7.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr10', 'gr15'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr2',
    name: 'Chicken Shish',
    description: 'Large chunks of chicken breast in a mildly spiced marinade cooked on the skewer over the grill. Served with rice and salad.',
    price: 1995,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive12.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr10', 'gr16'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr3',
    name: 'Lamb & Halloumi Kofte',
    description: 'Lamb kofte mixed with grated halloumi, onion, parsley, and Turkish spices, cooked over the grill. Served with rice and salad.',
    price: 2190,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive7.webp',
    allergens: ['Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['gr10', 'gr15'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr4',
    name: 'Chicken Wings',
    description: 'Marinated chicken wings cooked over charcoal grill. Served with rice and salad.',
    price: 1890,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive12.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr16', 'si1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr5',
    name: 'Lamb Shish',
    description: 'Tender marinated lamb pieces cooked on the skewer over the charcoal grill. Served with rice and salad.',
    price: 2295,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive7.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr10', 'gr15'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr6',
    name: 'Chicken Beyti',
    description: 'Minced chicken kofte with onion, parsley, and a blend of Turkish herbs and spices. Served with rice and salad.',
    price: 1930,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive12.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr16', 'gr7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr7',
    name: 'Mixed Beyti',
    description: 'Adana lamb kofte and chicken Beyti with onion, parsley, and a blend of Turkish herbs and spices. Served with rice and salad.',
    price: 1950,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive15.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr10', 'gr6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr8',
    name: 'Grilled Lamb Chops',
    description: 'Succulent lamb chops seasoned with Turkish herbs, cooked over the charcoal grill. Served with rice and salad.',
    price: 2595,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive3.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr15', 'si5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr9',
    name: 'Lamb Ribs',
    description: 'Lamb ribs seasoned with Turkish herbs, cooked over the charcoal grill. Served with rice and salad.',
    price: 2495,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive3.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr15', 'si5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr10',
    name: 'Mixed Grill',
    description: 'Selection of charcoal-grilled Chicken Shish, Lamb Shish, and Adana Kofte. Served with rice and salad.',
    price: 2390,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive9.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['gr15', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr11',
    name: 'Chicken Sarma',
    description: 'Minced chicken, garlic, and parsley wrapped in flatbread, sliced into pinwheels on yogurt, topped with mozzarella, Halep sauce, and butter. Served with rice and salad.',
    price: 1990,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive12.webp',
    allergens: ['Gluten', 'Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['gr12', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr12',
    name: 'Beyti Sarma',
    description: 'Charcoal-grilled minced lamb kofte rolled in flatbread with mozzarella, sliced into pinwheels on yogurt, topped with Halep sauce and butter. Served with rice and salad.',
    price: 1995,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive15.webp',
    allergens: ['Gluten', 'Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['gr11', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr13',
    name: 'Ali Nazik',
    description: 'Chilled garlic yogurt with grilled aubergine and pepper, topped with lamb shish. Served with rice and salad.',
    price: 2325,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive7.webp',
    allergens: ['Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['gr5', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr14',
    name: 'Olive Tree Special',
    description: 'Combination of Chicken Shish, Lamb Shish, Chicken Wings, Chicken Beyti, and Lamb Chop. Swap rice for fries +£2.00 or sweet potato fries +£2.75. Served with rice and salad.',
    price: 2550,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive15.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['si1', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr15',
    name: 'Mixed Sharing Platter',
    description: 'Chicken Shish, Lamb Shish, Lamb Ribs, Chicken Wings, Adana, and Chicken Beyti. For 2: £53.50 | For 4: £98.80.',
    price: 5350,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive9.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['cm14', 'de1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gr16',
    name: 'Chicken Sharing Platter',
    description: 'Chicken Shish, Marinated Wings, and Chicken Beyti Kofte, all chargrilled to perfection. For 2: £49.95 | For 4: £89.95.',
    price: 4995,
    category: 'From the Charcoal Grill',
    imageUrl: '/olive-tree/olive9.webp',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['cm14', 'de1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── PASTAS ───────────────────────────────────────────────────────────────
  {
    id: 'pa1',
    name: 'Anadolu Creamy Thyme Chicken Pasta',
    description: 'Rigatoni pasta in a creamy mushroom and thyme sauce with chicken, oven-baked.',
    price: 1750,
    category: 'Pastas',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Sulphites'],
    available: true,
    pairedItemIds: ['si3', 'pa2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pa2',
    name: 'Black Sea Seafood Pasta',
    description: 'Fettuccini in a rich tomato sauce with calamari, mussels, clams, and king prawns.',
    price: 1850,
    category: 'Pastas',
    imageUrl: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&q=80',
    allergens: ['Gluten', 'Molluscs', 'Crustaceans', 'Fish', 'Sulphites'],
    available: true,
    pairedItemIds: ['si3', 'pa3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pa3',
    name: 'Sebzeli Pasta',
    description: 'Fettuccini in onion, garlic, and basil tomato sauce with courgettes, mixed peppers, and plum tomatoes.',
    price: 1495,
    category: 'Pastas',
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&q=80',
    allergens: ['Gluten', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['si3', 'pa1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── VEGETARIAN & VEGAN ───────────────────────────────────────────────────
  {
    id: 'vv1',
    name: 'Falafel',
    description: 'Minced balls of chickpeas, broad beans, vegetables, and garlic with homemade tangy chutney and yogurt. Sarma option available. Served with sautéed potatoes.',
    price: 1795,
    category: 'Vegetarian & Vegan',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
    allergens: ['Sesame', 'Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vv4', 'hm5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vv2',
    name: 'Vegetarian Moussaka',
    description: 'Traditional Mediterranean dish with aubergine, potato, carrot, courgette, and onion, topped with béchamel sauce and melted mozzarella. Served with sautéed potatoes.',
    price: 1895,
    category: 'Vegetarian & Vegan',
    imageUrl: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vv4', 'si4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vv3',
    name: 'Imam Bayildi',
    description: 'Stuffed aubergine with onions, peppers, fresh tomatoes, chickpeas, and Halep sauce, topped with cheese. Vegan option available. Served with sautéed potatoes.',
    price: 1795,
    category: 'Vegetarian & Vegan',
    imageUrl: 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=800&q=80',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vv2', 'si6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'vv4',
    name: 'Vegetable Guvec',
    description: 'Chargrilled aubergine, red pepper, red onion, mushroom, and courgette with tomato sauce. Vegan. Served with sautéed potatoes.',
    price: 1795,
    category: 'Vegetarian & Vegan',
    imageUrl: '/olive-tree/olive1.webp',
    allergens: ['Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['vv1', 'vv2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── DESSERTS ─────────────────────────────────────────────────────────────
  {
    id: 'de1',
    name: 'Baklava',
    description: 'The most famous Turkish dessert from Gaziantep. Sweet pastry of layered filo dough filled with nuts and chopped pistachios, sweetened with sugar syrup.',
    price: 825,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=800&q=80',
    allergens: ['Gluten', 'Nuts', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de8', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de2',
    name: 'Kunefe',
    description: 'Traditional dessert from South East Turkey — shredded crispy filo dough filled with cheese, baked and finished with honey syrup. Please allow 15 minutes to bake.',
    price: 895,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1638202993928-7267aad84c31?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de3',
    name: 'Sutlac',
    description: 'Traditional Turkish rice pudding baked in the oven. Served cold.',
    price: 695,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    allergens: ['Milk', 'Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de7', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de4',
    name: 'Honeycomb Cheesecake',
    description: 'Creamy cheesecake on a cookie base with crunchy honeycomb pieces. Served with a scoop of vanilla ice cream.',
    price: 725,
    category: 'Desserts',
    imageUrl: '/olive-tree/olive2.webp',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de7', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de5',
    name: 'Olive Tree Sundae',
    description: 'Brownie pieces, whipped cream, vanilla ice cream and chocolate sauce.',
    price: 695,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Soya', 'Nuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de6',
    name: 'Triliche',
    description: 'A unique Turkish three milk cake — a perfect combination of cream and caramel.',
    price: 825,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de3', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de7',
    name: 'Ice Creams & Sorbets',
    description: '3 scoops. Choose from: Vanilla, Chocolate, Strawberry, Caramel, Lemon, Raspberry, or Mango.',
    price: 595,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1560008581-09826d1de69e?w=800&q=80',
    allergens: ['Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de4', 'de5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de8',
    name: 'Pista Leaves — Katmer',
    description: 'Traditional dessert from Gaziantep — very thin layers of phyllo dough stuffed with fine pistachio.',
    price: 825,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?w=800&q=80',
    allergens: ['Gluten', 'Nuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de1', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de9',
    name: 'Special Pistachio Cake',
    description: 'Roasted pistachios ground into fine crumbs, whisked into the cake batter.',
    price: 750,
    category: 'Desserts',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80',
    allergens: ['Gluten', 'Nuts', 'Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de7', 'sd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── COCKTAILS ─────────────────────────────────────────────────────────────
  {
    id: 'co1',
    name: 'Mediterranean Wave',
    description: 'Bacardi rum, sweet & sour, pineapple and mango juice, and a splash of Blue Curaçao.',
    price: 1050,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co2', 'co15'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co2',
    name: 'Green Monster',
    description: 'Bacardi Coconut, Midori, Banana Liqueur, Pineapple, Orange & Lime Juice.',
    price: 1050,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co1', 'co15'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co3',
    name: 'Rainbow',
    description: 'Grenadine, Peach Schnapps, orange juice, Vodka, Blue Curaçao.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co4', 'co16'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co4',
    name: 'Mai Tai',
    description: 'White Rum, Dark Rum, Lemon Juice, Almond Syrup, Grenadine.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800&q=80',
    allergens: ['Sulphites', 'Nuts'],
    available: true,
    pairedItemIds: ['co1', 'co3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co5',
    name: 'Only Way to Essex',
    description: 'Pink gin, strawberry purée, orange juice, pineapple juice, lime juice.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1621461898785-8c7efdc6a71e?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co17', 'co8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co6',
    name: 'Margarita',
    description: 'Tequila, Cointreau, sweet and sour, lime juice. Spicy option available.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1585641193060-5d7de9a0b0a0?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co19', 'co16'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co7',
    name: 'Bellini',
    description: 'Prosecco topped with mango or peach purée. Strawberry / Passion Fruit / Blackberry flavours available.',
    price: 895,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co9', 'co12'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co8',
    name: 'Bang On',
    description: 'Raspberry gin with cranberry, fresh berries and lime fizz.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co5', 'co17'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co9',
    name: 'Classical Aperol Spritz',
    description: 'Aperol, prosecco and fresh orange.',
    price: 975,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co7', 'co12'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co10',
    name: 'Espresso Martini',
    description: 'Vodka shaken with espresso, coffee liqueur and sugar syrup.',
    price: 1050,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1611199916608-2a2d1c10c4a8?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['de1', 'de9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co11',
    name: 'Long Island Ice Tea',
    description: 'Tequila, vodka, rum, gin and Cointreau with sour mix and cola.',
    price: 1090,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co1', 'co2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co12',
    name: 'Pornstar Martini',
    description: 'Vodka, passion-fruit liqueur and purée with vanilla-pineapple. Served with Prosecco.',
    price: 1050,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1615887480968-86b9bdcf1fda?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co7', 'co9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co13',
    name: 'Mojito',
    description: 'White rum muddled with mint, lime, brown sugar and soda. Strawberry and Passion Fruit flavours available.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1571950006673-09e56a66b7eb?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co14', 'mo5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co14',
    name: 'Sex on the Beach',
    description: 'Vodka blended with orange, cranberry and peach schnapps.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co3', 'co5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co15',
    name: 'Pina Colada',
    description: 'Spiced rum and Malibu in a creamy pineapple mix.',
    price: 1075,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3a5c1b7d4b30?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co1', 'co2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co16',
    name: 'Tequila Sunrise',
    description: 'Tequila poured over orange juice and grenadine.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1474540412665-1cdae210ae6b?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co3', 'co14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co17',
    name: 'Love Island',
    description: 'Strawberry gin with ginger beer, muddled berries and lemonade.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1621461898785-8c7efdc6a71e?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co8', 'co5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co18',
    name: 'Turkish Delight',
    description: 'Vodka with watermelon, passion-fruit purée, mint and lemonade.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co13', 'co8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'co19',
    name: 'Strawberry Daiquiri',
    description: 'White rum blended with strawberry purée and sweet-sour syrup.',
    price: 995,
    category: 'Cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1570598912132-0ba1dc952b7b?w=800&q=80',
    allergens: ['Sulphites'],
    available: true,
    pairedItemIds: ['co6', 'co13'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── MOCKTAILS ─────────────────────────────────────────────────────────────
  {
    id: 'mo1',
    name: 'Sunset Cooler',
    description: 'Pineapple juice, coconut cream, orange juice, grenadine.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo2', 'mo4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo2',
    name: 'Tropical Dream',
    description: 'Mango juice, watermelon syrup, cranberry juice.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1562155955-1cb2d73488d7?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo1', 'mo3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo3',
    name: 'Mango Chiller',
    description: 'Mango juice, agave syrup, blackcurrant and lemonade.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo2', 'mo4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo4',
    name: 'Tropical Bliss',
    description: 'Berries, lime, apple juice, mango juice.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo1', 'mo5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo5',
    name: 'Summer Breeze',
    description: 'Pomegranate juice, lime juice, lemonade and grenadine syrup.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo4', 'mo6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo6',
    name: 'Mediterranean Breeze',
    description: 'Passion-fruit, watermelon and cranberry shaken with lemonade.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1541614101331-1a5a3a194e92?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo5', 'mo7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo7',
    name: 'Green Apple',
    description: 'Citrus and apple juice with peach purée, mint and lemonade.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo8', 'mo5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mo8',
    name: 'Strawberry Kiss',
    description: 'Strawberry and watermelon purées topped with cranberry lemonade.',
    price: 695,
    category: 'Mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1570598912132-0ba1dc952b7b?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mo5', 'mo4'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── BEERS ─────────────────────────────────────────────────────────────────
  {
    id: 'be1',
    name: 'Efes Draught (Pint)',
    description: 'Efes Turkish lager on draught. Half pint £4.25.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be3', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be2',
    name: 'Cobra Draught (Pint)',
    description: 'Smooth Indian lager on draught. Half pint £4.25.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be1', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be3',
    name: 'Efes 500ml',
    description: 'Efes Turkish lager, bottled 500ml.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be4', 'gr5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be4',
    name: 'Tuborg 500ml',
    description: 'Tuborg lager, bottled 500ml.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be3', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be5',
    name: 'Peroni 330ml',
    description: 'Peroni Nastro Azzurro, 330ml. Gluten free option available.',
    price: 625,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
    allergens: ['Gluten'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['be3', 'gr2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be6',
    name: 'Corona 330ml',
    description: 'Corona Extra, refreshing lager, 330ml.',
    price: 595,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be4', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be7',
    name: 'Old Speckled Hen 500ml',
    description: 'Classic English ale, rich and malty, 500ml.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be8',
    name: 'London Pride 500ml',
    description: "Fuller's London Pride, premium ale, 500ml.",
    price: 645,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['be7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be9',
    name: 'Aspall Cyder 500ml',
    description: 'Aspall Premier Cru dry cider, 500ml.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['be10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be10',
    name: 'Kopparberg 500ml',
    description: 'Kopparberg mixed fruit cider, 500ml.',
    price: 695,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1566633806327-68e152aaf26d?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['be9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'be11',
    name: 'Becks Blue (Alcohol Free)',
    description: 'Alcohol-free beer, 275ml.',
    price: 525,
    category: 'Beers',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['mo1', 'sd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SOFT DRINKS ───────────────────────────────────────────────────────────
  {
    id: 'sd1',
    name: 'Soft Drinks',
    description: 'Coke, Diet Coke, Lemonade, Coke Zero, Sprite, Ginger Beer, Appletiser. £3.75.',
    price: 375,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1624552184280-9e73ab704bf7?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd2', 'ki1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd2',
    name: 'Juices',
    description: 'Apple, Orange, Pineapple, Mango, Cranberry, Peach, Pomegranate. £3.95.',
    price: 395,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd1', 'mo1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd3',
    name: 'Turkish Coffee',
    description: 'Traditional Turkish coffee. £3.50.',
    price: 350,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de1', 'de2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd4',
    name: 'Hot Beverages',
    description: 'Americano (£2.90), Latte / Cappuccino (£3.50), Espresso (from £2.75), Hot Chocolate (£3.50), English Tea (£2.50), Turkish Tea (£2.00), Green Tea (£2.50), Fresh Mint Tea (£2.95), Apple Tea (£2.50).',
    price: 290,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de1', 'de4', 'de9'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd5',
    name: 'Ayran',
    description: 'Traditional Turkish yogurt drink. £3.75.',
    price: 375,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1571167530149-c1105da4b38f?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['gr1', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd6',
    name: 'Homemade Lemonade',
    description: 'Freshly made homemade lemonade. £4.25.',
    price: 425,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd2', 'mo5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd7',
    name: 'Turkish Lemonade',
    description: 'Refreshing Turkish-style lemonade. £3.95.',
    price: 395,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd6', 'mo5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd8',
    name: 'Fizzy Orange',
    description: 'Sparkling orange soft drink. £3.95.',
    price: 395,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1624552184280-9e73ab704bf7?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd9',
    name: 'Salgam (Turnip Juice)',
    description: 'Traditional Turkish fermented turnip juice. £3.50.',
    price: 350,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1624552184280-9e73ab704bf7?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd5', 'gr1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd10',
    name: 'Still Water',
    description: 'Still mineral water. 330ml £3.25 | 750ml £4.25.',
    price: 325,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd11'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd11',
    name: 'Sparkling Water',
    description: 'Sparkling mineral water. 330ml £3.95 | 750ml £4.95.',
    price: 395,
    category: 'Soft Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd10'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── KIDS' MENU ────────────────────────────────────────────────────────────
  {
    id: 'ki1',
    name: 'Kids Chicken Meatballs',
    description: 'Served with rice and cucumber and carrot. Orange or blackcurrant squash included.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['ki7', 'ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki2',
    name: 'Kids Chicken Shish',
    description: 'Served with rice and cucumber and carrot. Orange or blackcurrant squash included.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['ki7', 'ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki3',
    name: 'Kids Chicken Wings',
    description: 'Served with rice and cucumber and carrot. Orange or blackcurrant squash included.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80',
    allergens: [],
    available: true,
    pairedItemIds: ['ki7', 'ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki4',
    name: 'Kids Fish Fingers',
    description: 'Served with chips and cucumber and carrot. Orange or blackcurrant squash included.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1609167830220-7164aa360951?w=800&q=80',
    allergens: ['Gluten', 'Fish', 'Eggs'],
    available: true,
    pairedItemIds: ['ki7', 'ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki5',
    name: 'Kids Chicken Nuggets',
    description: 'Served with chips and cucumber and carrot. Orange or blackcurrant squash included.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['ki7', 'ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki6',
    name: 'Kids Halloumi',
    description: 'Served with rice and cucumber and carrot. Orange or blackcurrant squash included.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ki7', 'ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki7',
    name: 'Kids Ice Cream',
    description: 'Choice of Chocolate, Vanilla, or Strawberry.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1560008581-09826d1de69e?w=800&q=80',
    allergens: ['Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ki8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ki8',
    name: 'Kids Chocolate Brownie',
    description: 'Served with ice cream.',
    price: 795,
    category: "Kids' Menu",
    imageUrl: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Nuts', 'Soya'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ki7'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SIDES ─────────────────────────────────────────────────────────────────
  {
    id: 'si1',
    name: 'Fries',
    description: 'Classic crispy fries.',
    price: 395,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['si2', 'wr1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'si2',
    name: 'Sweet Potato Fries',
    description: 'Crispy sweet potato fries.',
    price: 425,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1604908177522-ea42d8e3af69?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['si1', 'gr14'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'si3',
    name: 'Homemade Garlic Bread',
    description: 'Fresh homemade garlic bread.',
    price: 395,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1619985558574-e9ee73aaf7ee?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['pa1', 'pa2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'si4',
    name: 'Homemade Rice',
    description: 'Fluffy homemade rice.',
    price: 395,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['gr1', 'gr5', 'gr10'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'si5',
    name: 'Mashed Potatoes',
    description: 'Creamy homemade mashed potatoes.',
    price: 395,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1572441713132-c542fc4fe282?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['td4', 'td8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'si6',
    name: 'Sautéed Herbed Potatoes',
    description: 'Potatoes sautéed with herbs and butter.',
    price: 425,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800&q=80',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['fs1', 'fs2', 'fs3', 'fs4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'si7',
    name: 'Coban Salad',
    description: 'Fresh Turkish village salad with feta cheese.',
    price: 525,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    allergens: ['Milk', 'Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['gr1', 'gr10', 'td1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
