import type { MenuItem } from '../../src/types';

// Category ID prefix table
// Category           | Prefix | Example IDs
// -------------------|--------|------------
// starters           | st     | st1, st2
// chicken-steak      | cs     | cs1, cs2
// steaks             | sk     | sk1, sk2
// gold-collection    | gc     | gc1, gc2
// entree-cuts        | ec     | ec1, ec2
// burgers            | bg     | bg1, bg2
// entree-specials    | es     | es1, es2
// kids-menu          | km     | km1, km2
// extras             | xt     | xt1, xt2
// sides              | sd     | sd1, sd2
// sauces             | sc     | sc1, sc2
// mocktails          | mt     | mt1, mt2
// mojitos            | mj     | mj1, mj2
// milkshakes         | ms     | ms1, ms2
// soft-drinks        | sf     | sf1, sf2
// hot-drinks         | hd     | hd1, hd2
// desserts           | ds     | ds1, ds2

const NOW = Date.now();

export const menuItems: MenuItem[] = [
  // ── STARTERS ────────────────────────────────────────────────────────────
  {
    id: 'st1',
    name: 'Wagyu Sliders',
    description: 'Wagyu sliders with cheese and special sauce.',
    price: 1400,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sc1', 'sf1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st2',
    name: 'Lamb Chops Volaille',
    description: 'Succulent lamb chops served with lamb broth noodles with mint sauce.',
    price: 1400,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['sd2', 'sc4', 'sk1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st3',
    name: 'Noodles: Beef or Chicken',
    description: 'On a bed of spinach with pickled red cabbage tossed with our house made sauce.',
    price: 800,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80',
    allergens: ['Gluten', 'Soya'],
    available: true,
    pairedItemIds: ['sd6', 'sc1', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st4',
    name: 'Dynamite Shrimp or Chicken',
    description: 'On a bed of spinach with pickled red cabbage tossed in a tangy dynamite sauce.',
    price: 1200,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=800&q=80',
    allergens: ['Gluten', 'Crustaceans', 'Eggs', 'Milk'],
    available: true,
    pairedItemIds: ['sd3', 'sc1', 'sf1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st5',
    name: 'Dynamite Popcorn Chicken',
    description: 'Spicy chicken popcorn covered in cheese with a tangy dipping sauce.',
    price: 800,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['sd3', 'sc1', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st6',
    name: 'Haloumi',
    description: 'Fried or grilled — it\'s your choice.',
    price: 800,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd5', 'sd6', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st7',
    name: 'Entrée Wings',
    description: 'Spicy chicken wings marinated in your choice of: Buffalo | BBQ | Honey Mango | Peri Peri.',
    price: 1500,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80',
    allergens: ['Gluten', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sc1', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'st8',
    name: 'BBQ Ribs',
    description: 'Fine cut ribs marinated in BBQ sauce.',
    price: 1500,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    allergens: ['Gluten', 'Sulphites', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd3', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── CHICKEN STEAK ────────────────────────────────────────────────────────
  {
    id: 'cs1',
    name: 'Chicken Parmesan',
    description: 'Succulent chicken breast battered in seasoned panko breadcrumbs, topped with mushroom sauce and fried onions. Served with 2 sides of your choice.',
    price: 2500,
    category: 'chicken-steak',
    imageUrl: 'https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['sd1', 'sd3', 'sc3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cs2',
    name: 'Chicken Steak',
    description: 'Butterflied chicken breast grilled in spices, served with creamy spinach mash, sautéed mushrooms and one side of your choice.',
    price: 2200,
    category: 'chicken-steak',
    imageUrl: 'https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?w=800&q=80',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd2', 'sd5', 'sc3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'cs3',
    name: 'Firecracker Chicken Steak',
    description: 'Mouth-watering spicy steak lavished in firecracker sauce. Chargrilled in spices and served on a bed of creamy mash. Served with 2 sides of your choice.',
    price: 2200,
    category: 'chicken-steak',
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80',
    allergens: ['Milk', 'Mustard', 'Gluten'],
    available: true,
    pairedItemIds: ['sd1', 'sc1', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── STEAKS ───────────────────────────────────────────────────────────────
  {
    id: 'sk1',
    name: 'Tomahawk',
    description: '21-day dry aged Aberdeen Black Angus. Dry rubbed with Himalayan salt, pepper and sriracha, served with a side of your choice.',
    price: 10500,
    category: 'steaks',
    imageUrl: '/entree-steakhouse/hero.jpg',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk2',
    name: 'T-Bone',
    description: '21-day dry aged Aberdeen Black Angus. A classic cut served to perfection.',
    price: 3500,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd1', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk3',
    name: 'Fillet Mignon',
    description: '21-day dry aged Aberdeen Black Angus. 28-30 day fine cut dressed with fried onions and a mushroom purée sauce.',
    price: 4500,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc3', 'sc2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk4',
    name: 'Côte de Boeuf',
    description: '21-day dry aged Aberdeen Black Angus. Côte de boeuf marinated in salt and sriracha seasoning, served with sautéed veg.',
    price: 4500,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&q=80',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd5', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk5',
    name: 'Surf & Turf',
    description: 'Fillet mignon with prawns served with creamy mash and our signature pesto sauce.',
    price: 2800,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=800&q=80',
    allergens: ['Milk', 'Crustaceans', 'Mustard', 'Nuts'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk6',
    name: 'Fillet Mignon Special 8oz',
    description: '28-30 day dry aged fine cut, dressed with garlic sauce, fried onions and fine cut parsley.',
    price: 3400,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk7',
    name: 'Ribeye',
    description: 'Succulent ribeye served on a bed of creamy spinach mash with veg and one side of your choice.',
    price: 2600,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd2', 'sc2', 'sc3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk8',
    name: 'Sirloin',
    description: 'Succulent sirloin served on a bed of creamy spinach mash with one side of your choice.',
    price: 4500,
    category: 'steaks',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd1', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sk9',
    name: 'Sharing Tomahawk',
    description: 'Dry rubbed with herbs & spices, served with creamy mash, sun dried tomatoes finished with kale in balsamic vinegar.',
    price: 8500,
    category: 'steaks',
    imageUrl: '/entree-steakhouse/hero.jpg',
    allergens: ['Milk', 'Sulphites', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── GOLD COLLECTION ──────────────────────────────────────────────────────
  {
    id: 'gc1',
    name: 'Sharing Tomahawk: Gold Leaf',
    description: 'Shareable showstopper for large dining parties. Finely rubbed with herbs and spices, served with creamy mash finished with kale dressing, draped in edible gold leaf.',
    price: 12500,
    category: 'gold-collection',
    imageUrl: 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=800&q=80',
    allergens: ['Milk', 'Sulphites', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'gc2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gc2',
    name: 'Gold Leaf Black Angus Burger',
    description: 'Premium Black Angus burger full of flavour, crowned with edible gold leaf.',
    price: 4500,
    category: 'gold-collection',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sd4', 'sc1', 'gc1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'gc3',
    name: 'Gold Baklava',
    description: 'A luxury take on the classic — layered pistachio baklava drizzled with gold-dusted honey syrup.',
    price: 2000,
    category: 'gold-collection',
    imageUrl: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&q=80',
    allergens: ['Gluten', 'Nuts', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd1', 'hd2', 'ms1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── ENTRÉE CUTS ──────────────────────────────────────────────────────────
  {
    id: 'ec1',
    name: 'Japan Kobe: Rib Eye 10oz',
    description: 'One of the finest meats in the world from Black Castle Tajima Gyu. High marbling grade 6+, A5 quality certification, 300–600 days corn-fed. 48 hours notice required.',
    price: 14500,
    category: 'entree-cuts',
    imageUrl: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ec2',
    name: 'Japan Kobe: Fillet 9oz',
    description: 'One of the finest meats in the world from Black Castle Tajima Gyu. High marbling grade 6+, A5 quality certification, 300–600 days corn-fed. 48 hours notice required.',
    price: 14000,
    category: 'entree-cuts',
    imageUrl: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ec3',
    name: 'Australian Wagyu BMS 9+: Sirloin',
    description: 'Australian Wagyu with a high marbling score — melts in your mouth for a very rich texture.',
    price: 9900,
    category: 'entree-cuts',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ec4',
    name: 'Australian BMS 7-8: Fillet',
    description: 'Pinnacle of luxury — a succulent, rich, intensely marbled cut of beef that dissolves in your mouth.',
    price: 11000,
    category: 'entree-cuts',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── BURGERS ──────────────────────────────────────────────────────────────
  {
    id: 'bg1',
    name: '6oz Black Onyx Burger',
    description: 'Served with caramelised onions, tomato, double cheese and our special sauce.',
    price: 1600,
    category: 'burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sd4', 'sc1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bg2',
    name: 'Grilled Chicken Burger',
    description: 'Created on our special sauce in an American bun.',
    price: 1400,
    category: 'burgers',
    imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sd4', 'sc1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bg3',
    name: 'Philly Cheese Steak Sandwich',
    description: 'Succulent beef, caramelised onions and salsa topped with melted cheese in a hoagie roll.',
    price: 1900,
    category: 'burgers',
    imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sd4', 'sc1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'bg4',
    name: 'Mixed Meat Burger',
    description: 'Double patty burger — two full beef patties stacked high with all the trimmings.',
    price: 2500,
    category: 'burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sd4', 'sc1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── ENTRÉE SPECIALS ──────────────────────────────────────────────────────
  {
    id: 'es1',
    name: 'Chicken Parmesan Special',
    description: 'Succulent chicken breast battered in seasoned panko breadcrumbs, served on a bed of our Entrée signature chips.',
    price: 2700,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['sd3', 'sc3', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es2',
    name: 'Firecracker Chicken Steak Special',
    description: 'Mouth-watering spicy steak lavished in firecracker sauce. Chargrilled in spices and served on a bed of creamy mash.',
    price: 2500,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sc1', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es3',
    name: 'Slow Braised Lamb Shank',
    description: 'Tender, slow-cooked lamb shank infused with aromatic herbs and spices, served on a bed of creamy mashed potatoes drizzled with lamb broth gravy.',
    price: 3200,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&q=80',
    allergens: ['Milk', 'Gluten', 'Celery'],
    available: true,
    pairedItemIds: ['sd1', 'sd5', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es4',
    name: 'Tagliatelle Pasta',
    description: 'Choice of Beef, Chicken or Veg in the spice of your choice: Creamy, Mild Tomato or Spicy.',
    price: 1700,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd5', 'sc3', 'sf1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es5',
    name: 'Creamy Mushroom Tagliatelle Pasta',
    description: 'A decadent pasta tossed in a velvety garlic-infused cream sauce, loaded with sautéed mushrooms for a rich earthy flavour, finished with fresh parsley.',
    price: 1600,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sd5', 'sc3', 'sf1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es6',
    name: 'Fillet Mignon Special 8oz',
    description: '28-day dry aged steak dressed with garlic sauce, fried onions and served on a bed of garlic creamy mash.',
    price: 3600,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es7',
    name: 'Surf & Turf 8oz',
    description: 'A beautifully marbled fillet mignon grilled to perfection, served on a bed of garlic creamy mash with garlic butter sauce and pan-seared lobster tail.',
    price: 4800,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1594041680534-e8c8cdebd659?w=800&q=80',
    allergens: ['Milk', 'Crustaceans', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es8',
    name: 'Baked Salmon',
    description: 'Beautifully delicate spiced fillet of salmon served with garlic creamy mashed potatoes, seasonal veg and garlic butter sauce.',
    price: 2800,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    allergens: ['Fish', 'Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd5', 'sc5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es9',
    name: 'Delectable Ribeye',
    description: 'Succulent ribeye steak grilled to perfection, layed on a bed of Entrée signature chips, smothered with a creamy mushroom sauce, with a side of coleslaw.',
    price: 3800,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80',
    allergens: ['Milk', 'Gluten', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sc3', 'sc2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es10',
    name: 'Pollo Mushroom Steak',
    description: 'Beautifully marinated grilled chicken steak layed on a bed of Entrée signature chips, topped with creamy mushroom sauce, accompanied with coleslaw.',
    price: 2800,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?w=800&q=80',
    allergens: ['Milk', 'Gluten', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sc3', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es11',
    name: 'Blow Out',
    description: 'A delectable ribeye, a chicken steak, two lamb chops and 3 pieces of dynamite chicken with a portion of entrée chips and coleslaw.',
    price: 2500,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sc1', 'sc2', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es12',
    name: 'Beef Katsu Curry',
    description: 'Tender, breaded and crispy fried beef, served over a bed of steamed jasmine rice, smothered in a rich, velvety Japanese curry sauce.',
    price: 2700,
    category: 'entree-specials',
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Soya', 'Milk'],
    available: true,
    pairedItemIds: ['sd10', 'sf1', 'sf2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'es13',
    name: 'Sharing Tomahawk 12oz',
    description: 'Comes with 4 sides of your choice. Dry rubbed with herbs & spices.',
    price: 8500,
    category: 'entree-specials',
    imageUrl: '/entree-steakhouse/hero.jpg',
    allergens: ['Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['sd1', 'sd2', 'sc2', 'sc4'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── KIDS MENU ────────────────────────────────────────────────────────────
  {
    id: 'km1',
    name: 'Cheeseburger',
    description: 'Kids cheeseburger with chips and juice.',
    price: 800,
    category: 'kids-menu',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Mustard'],
    available: true,
    pairedItemIds: ['sd3', 'sf3', 'ms1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'km2',
    name: 'Chicken Goujons',
    description: 'Kids chicken goujons with chips and juice.',
    price: 600,
    category: 'kids-menu',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    available: true,
    pairedItemIds: ['sd3', 'sc1', 'sf3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'km3',
    name: 'Kids Pasta',
    description: 'Kids pasta with chips and juice.',
    price: 600,
    category: 'kids-menu',
    imageUrl: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sf3', 'ms1', 'ds1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── EXTRAS ───────────────────────────────────────────────────────────────
  {
    id: 'xt1',
    name: 'Fried Egg',
    description: 'A perfectly fried egg — great on burgers or alongside your steak.',
    price: 300,
    category: 'extras',
    imageUrl: 'https://images.unsplash.com/photo-1494961104209-3c223057bd26?w=800&q=80',
    allergens: ['Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'bg4', 'sk2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'xt2',
    name: 'Fried Onions',
    description: 'Crispy golden fried onions.',
    price: 400,
    category: 'extras',
    imageUrl: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=800&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk3', 'bg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'xt3',
    name: 'Extra Sauce',
    description: 'An extra portion of any sauce of your choice.',
    price: 300,
    category: 'extras',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80',
    allergens: ['Milk', 'Mustard'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk2', 'es6'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SIDES ────────────────────────────────────────────────────────────────
  {
    id: 'sd1',
    name: 'Garlic Creamy Mash',
    description: 'Velvety mashed potato with roasted garlic and cream.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk3', 'es3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd2',
    name: 'Spinach Creamy Mash',
    description: 'Creamy mash blended with wilted baby spinach.',
    price: 500,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1541014741259-de529411b96a?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk7', 'sk8', 'cs2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd3',
    name: 'In-House Chips',
    description: 'Our signature hand-cut chips, crispy on the outside, fluffy inside.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1630431341973-02e1b662ec35?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'bg2', 'cs1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd4',
    name: 'Entrée Spicy Chips',
    description: 'Our signature chips tossed in our house spice blend.',
    price: 500,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1630431341973-02e1b662ec35?w=800&q=80',
    allergens: ['Mustard'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'bg4', 'cs3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd5',
    name: 'Steamed Veggies',
    description: 'Seasonal steamed vegetables.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk4', 'es8'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd6',
    name: 'Sauté Mushrooms',
    description: 'Pan-fried mushrooms in garlic and herb butter.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk2', 'cs2', 'es6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd7',
    name: 'Macaroni & Cheese',
    description: 'Rich and creamy mac and cheese.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1612152328957-7e1b13b42677?w=800&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'bg1', 'cs1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd8',
    name: 'Corn on the Cob',
    description: 'Chargrilled corn on the cob with seasoned butter.',
    price: 400,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'es11', 'km1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd9',
    name: 'Cheesy Corn',
    description: 'Sweet corn smothered in melted cheese.',
    price: 300,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'km2', 'bg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd10',
    name: 'Spicy Rice',
    description: 'Aromatic spiced rice.',
    price: 500,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['es12', 'cs2', 'st4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sd11',
    name: 'Coleslaw',
    description: 'House-made creamy coleslaw.',
    price: 300,
    category: 'sides',
    imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800&q=80',
    allergens: ['Eggs', 'Mustard'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'bg4', 'es9'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SAUCES ───────────────────────────────────────────────────────────────
  {
    id: 'sc1',
    name: "Shirley's Firecracker Sauce",
    description: 'A signature house-made fiery sauce with a kick.',
    price: 250,
    category: 'sauces',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80',
    allergens: ['Mustard'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st4', 'st7', 'bg1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sc2',
    name: 'Peppercorn Sauce',
    description: 'Classic creamy peppercorn sauce.',
    price: 250,
    category: 'sauces',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk3', 'es6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sc3',
    name: 'Mushroom Sauce',
    description: 'Rich, creamy mushroom sauce.',
    price: 250,
    category: 'sauces',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk2', 'sk7', 'cs1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sc4',
    name: 'Gravy',
    description: 'Rich beef gravy.',
    price: 400,
    category: 'sauces',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80',
    allergens: ['Gluten', 'Celery'],
    available: true,
    pairedItemIds: ['sk2', 'es3', 'sd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sc5',
    name: 'Garlic Butter',
    description: 'House-made garlic compound butter.',
    price: 200,
    category: 'sauces',
    imageUrl: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk5', 'es7'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── MOCKTAILS ────────────────────────────────────────────────────────────
  {
    id: 'mt1',
    name: 'Pina Colada',
    description: 'A classic combination of creamy coconut and chunks of fresh pineapple.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'bg1', 'ds1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt2',
    name: 'The Entrée',
    description: 'Authentic dragon fruit purée balanced with citrus lime, topped with lemonade.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'st6', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt3',
    name: 'Berry Queen',
    description: 'Freshly muddled raspberry and strawberry, squeezed lime, topped with lemonade.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds4', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt4',
    name: "Cherry's Passion",
    description: 'Authentic morello cherry syrup mixed with the classic taste of Coke.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'st7', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt5',
    name: 'Ballers',
    description: 'Cranberry juice, lemonade, orange juice and Red Bull.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st7', 'bg4', 'ds2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt6',
    name: 'Mango Daiquiri',
    description: 'Refreshing blend of mango chunks, lime and mango syrup.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'st4', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt7',
    name: 'Strawberry Daiquiri',
    description: 'Refreshing blend of garden strawberries, lime and strawberry syrup.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds3', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt8',
    name: 'Bubblegum Daiquiri',
    description: 'Refreshing blend of bubble gum syrup, lime and blue curaçao.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'km2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt9',
    name: 'Peardrops',
    description: 'Smashed fresh blueberries, raspberries, lime, lemonade and pear purée.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds4', 'ds1', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt10',
    name: 'Sunset Love',
    description: 'A taste of peach with strawberries.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds3', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt11',
    name: "Shrek's Magic",
    description: 'Mixture of mango and bubblegum daiquiris.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'km3', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt12',
    name: 'Deep Ocean',
    description: 'A collection of fresh berries mixed with blue curaçao, topped with lemonade.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st6', 'ds4', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt13',
    name: 'Tropical Rush',
    description: 'Orange-based mocktail mixed with mango syrup, freshly squeezed lime, topped with lemonade.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'bg2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mt14',
    name: 'Peach on the Rocks',
    description: 'Mouth-watering peach flavour, mint leaves and freshly squeezed lemons and lemonade.',
    price: 1200,
    category: 'mocktails',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds3', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── MOJITOS ──────────────────────────────────────────────────────────────
  {
    id: 'mj1',
    name: 'Kiwi Mojito',
    description: 'Fresh kiwi, lemonade, lime and mint.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st6', 'ds3', 'bg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj2',
    name: 'Red Bull Mojito',
    description: 'Red Bull, lemonade, mint and lime.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st7', 'bg4', 'es11'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj3',
    name: 'Billionaire',
    description: 'Electric blue mocktail, blue curaçao, lemonade, mint and lime.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['gc1', 'gc2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj4',
    name: 'Classic Mojito',
    description: 'Fresh cool mint, freshly squeezed lime and soda water.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'sk2', 'st1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj5',
    name: 'Strawberry Mojito',
    description: 'Fresh strawberries with lime and lemonade and mint.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds3', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj6',
    name: 'Passionfruit Mango',
    description: 'Passionfruit mixed with mango syrup, cool mint, citrus lime and lemonade.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st4', 'bg2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj7',
    name: 'Peach Raspberry Lemonade',
    description: 'Raspberries paired with peach syrup, cool mint, citrus lime and lemonade.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds4', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'mj8',
    name: 'Apple Mojito',
    description: 'Granny Smith apple syrup, muddled with cool mint, citrus lime and lemonade.',
    price: 1195,
    category: 'mojitos',
    imageUrl: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'bg1', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── MILKSHAKES ───────────────────────────────────────────────────────────
  {
    id: 'ms1',
    name: 'Chocolate Love',
    description: 'Rich chocolate milkshake.',
    price: 1000,
    category: 'milkshakes',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds3', 'km1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ms2',
    name: 'Strawberry Delight',
    description: 'Fresh strawberry milkshake.',
    price: 1000,
    category: 'milkshakes',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds4', 'km2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ms3',
    name: 'Taste of Madagascan',
    description: 'Madagascan vanilla milkshake.',
    price: 1000,
    category: 'milkshakes',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds2', 'ds3', 'km3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ms4',
    name: 'Ferrero Rocher',
    description: 'Indulgent Ferrero Rocher milkshake with hazelnut and chocolate.',
    price: 1000,
    category: 'milkshakes',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80',
    allergens: ['Milk', 'Nuts', 'Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds5', 'km1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── SOFT DRINKS ──────────────────────────────────────────────────────────
  {
    id: 'sf1',
    name: 'Coca Cola',
    description: 'Ice cold Coca Cola.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'bg4', 'st7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf2',
    name: 'Diet Coke',
    description: 'Ice cold Diet Coke.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['bg1', 'bg2', 'st7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf3',
    name: 'Fanta',
    description: 'Ice cold Fanta.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'km2', 'bg2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf4',
    name: 'Lemonade',
    description: 'Freshly made lemonade.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st6', 'km3', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf5',
    name: 'Appletizer',
    description: 'Sparkling apple juice.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'bg2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf6',
    name: 'J2O',
    description: 'J2O fruit drink.',
    price: 500,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'km3', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf7',
    name: 'Red Bull',
    description: 'Red Bull energy drink.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mj2', 'mt5', 'bg4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf8',
    name: 'Orange Juice',
    description: 'Freshly squeezed orange juice.',
    price: 500,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['st1', 'km1', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf9',
    name: 'Pineapple Juice',
    description: 'Fresh pineapple juice.',
    price: 500,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['mt1', 'st4', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf10',
    name: 'Apple Juice',
    description: 'Clear apple juice.',
    price: 500,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['km1', 'km3', 'st6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'sf11',
    name: 'Water',
    description: 'Still or sparkling water.',
    price: 400,
    category: 'soft-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['sk1', 'es3', 'ds1'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── HOT DRINKS ───────────────────────────────────────────────────────────
  {
    id: 'hd1',
    name: 'Tea',
    description: 'Classic English breakfast tea.',
    price: 400,
    category: 'hot-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hd2',
    name: 'Green Tea',
    description: 'Light and refreshing green tea.',
    price: 400,
    category: 'hot-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds5', 'gc3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hd3',
    name: 'Latte',
    description: 'Espresso with steamed milk.',
    price: 400,
    category: 'hot-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hd4',
    name: 'Mint Tea',
    description: 'Soothing fresh mint tea.',
    price: 400,
    category: 'hot-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'gc3', 'ds4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hd5',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk and froth.',
    price: 500,
    category: 'hot-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds2', 'ds3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'hd6',
    name: 'Iced Coffee',
    description: 'Chilled espresso over ice.',
    price: 500,
    category: 'hot-drinks',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    allergens: ['Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['ds1', 'ds3', 'ds5'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── DESSERTS ─────────────────────────────────────────────────────────────
  {
    id: 'ds1',
    name: 'Chocolate Fudge Cake',
    description: 'Served with ice cream, Belgian chocolate sauce and white chocolate sauce.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd3', 'hd5', 'ms1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds2',
    name: 'Biscoff Cheesecake',
    description: 'Served with vanilla ice cream and white chocolate sauce.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd1', 'hd3', 'ms3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds3',
    name: 'Chocolate Brownie',
    description: 'Served with Magnum and topped up with Belgian and white chocolate sauce.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd5', 'ms1', 'ms4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds4',
    name: 'Baklava with Ice Cream',
    description: 'Fresh pistachio baklava served with gelato ice cream.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&q=80',
    allergens: ['Gluten', 'Nuts', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd2', 'hd4', 'ms3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds5',
    name: 'Kunafa Brownie Bliss',
    description: 'A Kunafa Brownie with Magnum — a fudgy brownie, crispy Kunafa and a creamy Magnum bar, drizzled with chocolate for a rich, indulgent treat.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk', 'Nuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd2', 'hd4', 'ms1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds6',
    name: 'Vanilla New York Cheesecake',
    description: 'Made in house. Topped with white chocolate sauce and strawberry sauce.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd3', 'hd5', 'ms2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds7',
    name: 'Chocolate Fondant',
    description: 'Served with Madagascan vanilla ice cream.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd3', 'ms1', 'ms3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ds8',
    name: 'Red Velvet Cheesecake',
    description: 'Served with white chocolate sauce.',
    price: 1295,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&q=80',
    allergens: ['Gluten', 'Eggs', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['hd3', 'hd5', 'ms2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
