import { MenuItem, RestaurantConfig } from './types';

export const DEFAULT_CONFIG: RestaurantConfig = {
  name: 'arco Bar & Ristorante',
  logo: '/arco/logo.avif',
  primaryColour: '#A83A35',
  accentColour: '#1C1B19',
  welcomeMessage: 'Authentic Italian flavours, crafted with passion.',
  lastUpdated: Date.now(),
};

const NOW = Date.now();

export const DEFAULT_MENU_ITEMS: MenuItem[] = [

  // ── STARTERS & NIBBLES ──────────────────────────────────────────────────

  {
    id: 's1',
    name: 'Marinated Olives',
    description: 'Mixed green and black olives marinated in herbs and olive oil. A perfect Italian table welcome.',
    price: 400,
    category: 'starters',
    imageUrl: '/arco/unnamed-6.jpg',
    allergens: [],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['s7', 'd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's2',
    name: 'Garlic Bread',
    description: 'Freshly baked ciabatta with garlic butter, golden and crisp on the outside, soft within.',
    price: 500,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['s5', 'p3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's3',
    name: 'Garlic Bread Speciale',
    description: 'Ciabatta with garlic butter, topped with mozzarella and sun-blushed tomato. Rich and satisfying.',
    price: 600,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['s5', 'p3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's4',
    name: 'Bread & Oil',
    description: 'Warm ciabatta served with premium extra virgin olive oil and aged balsamic for dipping.',
    price: 500,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['s1', 'd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's5',
    name: 'Meatballs',
    description: 'Handmade beef meatballs in rich tomato ragu, served on toasted ciabatta with melted mozzarella.',
    price: 900,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['p7', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's6',
    name: 'Bruschetta',
    description: 'Toasted ciabatta with basil pesto, fresh tomato, red onion, Parmesan and a balsamic glaze.',
    price: 900,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['s1', 'd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's7',
    name: 'Calamari',
    description: 'Lightly fried calamari rings, crisp and tender, served with fresh salad, sweet chilli and lemon.',
    price: 900,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Molluscs'],
    available: true,
    pairedItemIds: ['d1', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's8',
    name: 'Garlic Mushrooms',
    description: 'Sautéed mushrooms in garlic and cream, piled high on toasted ciabatta with fresh parsley.',
    price: 900,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['p5', 'p6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's9',
    name: 'Chicken Liver Pâté',
    description: 'Smooth chicken liver pâté on toasted ciabatta with caramelised onions and a butter glaze.',
    price: 900,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['d1', 'm1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's10',
    name: 'Salsiccia',
    description: 'Grilled Italian pork sausage with onions, chilli, garlic and rich tomato sauce on ciabatta.',
    price: 900,
    category: 'starters',
    imageUrl: '/arco/unnamed-7.jpg',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['p12', 'd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's11',
    name: 'Tempura Prawns',
    description: 'Tiger prawns in a light, crispy tempura batter, served with fresh salad, sweet chilli and lemon.',
    price: 1200,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Crustaceans'],
    available: true,
    pairedItemIds: ['p4', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's12',
    name: 'Mushroom Arancini',
    description: 'Golden risotto balls filled with mushrooms, garlic and Parmesan, crisp outside and creamy within.',
    price: 900,
    category: 'starters',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['p5', 'd1'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 's13',
    name: 'Rope Grown Mussels',
    description: 'Fresh rope-grown mussels steamed in chilli and tomato sauce, served with toasted ciabatta and lemon.',
    price: 1000,
    category: 'starters',
    imageUrl: '/arco/unnamed-11.jpg',
    allergens: ['Gluten', 'Molluscs'],
    available: true,
    pairedItemIds: ['p4', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── MAINS ────────────────────────────────────────────────────────────────

  {
    id: 'm1',
    name: 'Lamb Shank',
    description: 'Slow-cooked lamb shank, falling off the bone, served on creamy mash with seasonal vegetables and a rich red wine jus.',
    price: 2400,
    category: 'mains',
    imageUrl: '/arco/unnamed-3.jpg',
    allergens: ['Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d1', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'm2',
    name: 'Short Rib',
    description: 'Braised beef short rib, deeply flavoured and tender, on smooth mash with seasonal vegetables and red wine jus.',
    price: 2300,
    category: 'mains',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    allergens: ['Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'm3',
    name: 'Salmon & Prawn Thermidor',
    description: 'Pan-roasted salmon and king prawns in a classic thermidor sauce, with baby potatoes and seasonal vegetables.',
    price: 2400,
    category: 'mains',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish', 'Crustaceans', 'Milk', 'Eggs'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'm4',
    name: 'Pan-Fried Seabass',
    description: 'Fillet of sea bass pan-fried to a crisp skin, resting on saffron risotto with a cream finish.',
    price: 2200,
    category: 'mains',
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80',
    allergens: ['Fish', 'Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'm5',
    name: 'Pollo Milanese',
    description: 'Fried chicken breast topped with melted mozzarella and Parma ham, in a rich tomato sauce with baby potatoes and vegetables.',
    price: 2000,
    category: 'mains',
    imageUrl: '/arco/unnamed-10.jpg',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'm6',
    name: 'Pollo Diane',
    description: 'Chicken breast in a creamy Diane sauce with mushrooms, served with baby potatoes and seasonal vegetables.',
    price: 2000,
    category: 'mains',
    imageUrl: '/arco/unnamed-10.jpg',
    allergens: ['Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── PASTA & RISOTTO ──────────────────────────────────────────────────────

  {
    id: 'p1',
    name: 'Carbonara',
    description: 'Linguine with crispy pancetta, Parmesan, egg yolk, cream and cracked black pepper. A Roman classic.',
    price: 1900,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p2',
    name: 'Seafood Linguine',
    description: 'Linguine with fresh salmon, king prawns and mussels in a spiced tomato and chilli sauce.',
    price: 2300,
    category: 'pasta',
    imageUrl: '/arco/unnamed-2.jpg',
    allergens: ['Gluten', 'Fish', 'Crustaceans', 'Molluscs'],
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p3',
    name: 'Lasagne',
    description: 'Layers of egg pasta with slow-cooked beef ragu, rich béchamel and golden melted mozzarella and Parmesan.',
    price: 1900,
    category: 'pasta',
    imageUrl: '/arco/unnamed-12.jpg',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p4',
    name: 'Linguine Gamberi',
    description: 'Linguine with king prawns in a Napoli tomato sauce with garlic and a hint of chilli.',
    price: 2200,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Crustaceans'],
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p5',
    name: 'Pea & Mushroom Risotto',
    description: 'Creamy Arborio risotto with sautéed mushrooms, garden peas, red onion and Parmesan.',
    price: 1800,
    category: 'pasta',
    imageUrl: '/arco/unnamed-8.jpg',
    allergens: ['Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d1', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p6',
    name: 'Risotto Gamberi',
    description: 'Arborio risotto with king prawns, red onion and a touch of chilli, finished with Parmesan.',
    price: 2200,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&auto=format&fit=crop&q=80',
    allergens: ['Crustaceans', 'Milk'],
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p7',
    name: 'Bolognese',
    description: 'Linguine with a slow-cooked beef ragu, fresh basil and aged Parmesan. A timeless classic.',
    price: 1900,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p8',
    name: 'Pollo Pesto Penne',
    description: 'Penne with tender chicken, basil pesto, cream, garlic and Parmesan. Simple, fragrant, satisfying.',
    price: 1900,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Nuts'],
    available: true,
    pairedItemIds: ['d3', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p9',
    name: 'Amatriciana',
    description: 'Linguine with Italian sausage, red onion, chilli, tomato sauce and Parmesan. Bold and rustic.',
    price: 2100,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1598866594230-a7c12756260f?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p10',
    name: 'Arrabiata',
    description: 'Penne in a fiery tomato sauce with red onion, chilli, fresh tomato and Parmesan. Punchy and vibrant.',
    price: 1700,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['d1', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p11',
    name: 'Salmon & Broccoli Linguine',
    description: 'Linguine with flaked salmon, tender broccoli, cream, lemon and garlic. Light and elegant.',
    price: 2200,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Fish', 'Milk'],
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p12',
    name: 'Cajun Pollo Penne',
    description: 'Penne with chicken, red onion, chilli and cream in a smoky Cajun-spiced sauce with Parmesan.',
    price: 2000,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p13',
    name: 'Quatro Formagi Tortellini',
    description: 'Tortellini filled with four cheeses — mozzarella, ricotta, Parmesan and cheddar — in a rich tomato sauce.',
    price: 1800,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['d3', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p14',
    name: 'Pollo Pepperoni Penne',
    description: 'Penne with chicken, pepperoni, cream, paprika, garlic and Parmesan. Rich and deeply savoury.',
    price: 1900,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'p15',
    name: 'Beef Stroganoff',
    description: 'Penne with tender beef strips, mushrooms, mustard, cream, onion and Parmesan. Hearty and warming.',
    price: 1900,
    category: 'pasta',
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Mustard'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── PIZZA ────────────────────────────────────────────────────────────────

  {
    id: 'pz1',
    name: 'Margherita',
    description: 'The classic. Pizza sauce, melted mozzarella and fragrant fresh basil. Simple perfection.',
    price: 1500,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz2',
    name: 'Prosciutto Funghi',
    description: 'Pizza sauce with mozzarella, pancetta and earthy mushrooms. Salty, savoury, deeply Italian.',
    price: 1800,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz3',
    name: 'Giardino',
    description: 'Vegetarian pizza with mozzarella, onions, mushrooms, sun-blushed tomato and basil pesto.',
    price: 1700,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Nuts'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['d3', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz4',
    name: 'Carne',
    description: 'A meat feast — pepperoni, salami, spicy beef and chicken on tomato sauce and mozzarella.',
    price: 1900,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz5',
    name: 'Diavola',
    description: 'Hot and fiery — pepperoni, chicken, chilli, sun-blushed tomato and red onion on mozzarella.',
    price: 1900,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz6',
    name: 'Picante',
    description: 'Spicy beef, red onion and chilli on tomato sauce and melted mozzarella. Not for the faint-hearted.',
    price: 1800,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz7',
    name: 'Pepperoni',
    description: 'Classic pepperoni pizza. Generous slices of pepperoni on tomato sauce and melted mozzarella.',
    price: 1700,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz8',
    name: 'Frutti di Mare',
    description: 'A seafood pizza with tuna, anchovies, salmon and red onion on tomato sauce and mozzarella.',
    price: 1900,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Fish'],
    available: true,
    pairedItemIds: ['d2', 'd4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pz9',
    name: 'Salciccia',
    description: 'Italian sausage, red onion, green peppers and mushrooms on tomato sauce and mozzarella.',
    price: 1800,
    category: 'pizza',
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk'],
    available: true,
    pairedItemIds: ['d1', 'd3'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── DESSERTS ─────────────────────────────────────────────────────────────

  {
    id: 'de1',
    name: 'Eton Mess',
    description: 'Crushed meringue, whipped cream and fresh strawberries folded together. Light, sweet and very British-Italian.',
    price: 700,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=80',
    allergens: ['Eggs', 'Milk'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['dr3', 'dr4'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de2',
    name: 'Chocolate Brownie',
    description: 'Warm, fudgy dark chocolate brownie with a crisp top. Served with a scoop of vanilla ice cream.',
    price: 700,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs', 'Soya'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['dr3', 'dr5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de3',
    name: 'Strawberry Cheesecake',
    description: 'Creamy baked cheesecake on a biscuit base, topped with fresh strawberry compote.',
    price: 700,
    category: 'desserts',
    imageUrl: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten', 'Milk', 'Eggs'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['dr4', 'dr5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'de4',
    name: 'Ice Cream',
    description: 'Two scoops of artisan ice cream. Choose from vanilla, chocolate or strawberry.',
    price: 500,
    category: 'desserts',
    imageUrl: '/arco/unnamed-13.jpg',
    allergens: ['Milk', 'Eggs'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['dr4', 'dr5'],
    createdAt: NOW,
    updatedAt: NOW,
  },

  // ── DRINKS ───────────────────────────────────────────────────────────────

  {
    id: 'dr1',
    name: 'Aperol Spritz',
    description: 'Aperol, Prosecco and a splash of soda over ice with a slice of orange. The Italian aperitivo.',
    price: 980,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1560508180-03f285f67ded?w=800&auto=format&fit=crop&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['s1', 's6'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr2',
    name: 'Passione Martini',
    description: 'Passoa, vodka, vanilla syrup, pineapple juice, lemon juice and Passione purée. Tropical and bold.',
    price: 980,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de1', 'de3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr3',
    name: 'Caramello Espresso Martini',
    description: 'Vodka, Tia Maria, caramel syrup and a freshly pulled espresso shot, shaken and strained.',
    price: 980,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de2', 'de3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr4',
    name: 'Limoncello Iced Tea',
    description: 'Vodka, gin, rum, lemon juice, sugar syrup, limoncello and lemonade. Refreshing and citrus-bright.',
    price: 980,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['s6', 's7'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr5',
    name: 'Strawberry Daiquiri',
    description: 'White rum, fresh strawberry purée, lemon juice and sugar syrup, blended smooth and served chilled.',
    price: 980,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80',
    allergens: [],
    isVegetarian: true,
    available: true,
    pairedItemIds: ['de1', 'de3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr6',
    name: 'Sangiovese — Glass of Red',
    description: 'Puglia I.G.T. 12%. Cherry Sangiovese with hints of blueberry Merlot. Medium-bodied and food-friendly.',
    price: 890,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&auto=format&fit=crop&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['m1', 'p3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr7',
    name: 'Pinot Grigio — Glass of White',
    description: 'Antonio Rubini 11%. Rich pear drop and elderflower notes with a lingering apple finish.',
    price: 890,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['m3', 'p2'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr8',
    name: 'Botega Prosecco',
    description: 'Italian Prosecco DOC. Light, crisp and elegant with fine bubbles and delicate apple and pear notes.',
    price: 850,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80',
    allergens: ['Sulphites'],
    isVegetarian: true,
    isGlutenFree: true,
    available: true,
    pairedItemIds: ['s6', 'de3'],
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'dr9',
    name: 'Peroni',
    description: 'Italian lager 5% (330ml bottle). Crisp, clean and refreshing — the definitive Italian beer.',
    price: 510,
    category: 'drinks',
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&auto=format&fit=crop&q=80',
    allergens: ['Gluten'],
    available: true,
    pairedItemIds: ['pz4', 'pz5'],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const CATEGORY_FALLBACK_IMAGES = {
  starters: '/arco/unnamed-6.jpg',
  mains: '/arco/unnamed-3.jpg',
  pasta: '/arco/unnamed-2.jpg',
  pizza: '/arco/unnamed-5.jpg',
  desserts: '/arco/unnamed-13.jpg',
  drinks: '/arco/unnamed-15.jpg',
};
